"""
CoinMarketCap data fetcher for the crypto dashboard.
Fetches real-time listings, global metrics, and Fear & Greed index,
converts USD prices to IRR via CMC's built-in convert parameter,
and stores everything in PostgreSQL.

Daily OHLCV candles are self-generated by aggregating ticker snapshots
(CMC free tier does not include historical OHLCV).
"""

import json
import logging
from datetime import UTC, date, datetime, timedelta
from decimal import Decimal

import httpx
from sqlalchemy import func, select
from sqlalchemy.dialects.postgresql import insert

from config.settings import (
    CMC_API_KEY,
    CMC_BASE_URL,
    CRYPTO_TICKER_RETENTION_HOURS,
)
from database.models import (
    CryptoGlobalMetrics,
    CryptoOHLCV,
    CryptoTicker,
    Security,
)

logger = logging.getLogger(__name__)

# Redis pub/sub channel for live crypto updates
REDIS_CHANNEL_CRYPTO = "tse:live:crypto"

# Fear & Greed API endpoint (free public API, no credits)
FEAR_GREED_URL = "https://api.alternative.me/fng/"


# ---------------------------------------------------------------------------
# CoinMarketCap Client
# ---------------------------------------------------------------------------


class CMCClient:
    """Synchronous HTTP client for the CoinMarketCap Pro API."""

    def __init__(
        self,
        api_key: str = CMC_API_KEY,
        base_url: str = CMC_BASE_URL,
        timeout: float = 15.0,
    ):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.timeout = timeout
        self._headers = {
            "X-CMC_PRO_API_KEY": self.api_key,
            "Accept": "application/json",
        }

    def _get(self, path: str, params: dict | None = None) -> dict:
        """Execute a GET request and return the parsed JSON response."""
        url = f"{self.base_url}{path}"
        with httpx.Client(timeout=self.timeout) as client:
            resp = client.get(url, params=params, headers=self._headers)
            resp.raise_for_status()
            data = resp.json()
        status = data.get("status", {})
        if status.get("error_code", 0) != 0:
            raise RuntimeError(
                f"CMC API error on {path}: code={status.get('error_code')}, "
                f"msg={status.get('error_message')}"
            )
        return data.get("data", {})

    def fetch_listings(self, limit: int = 30) -> list[dict]:
        """
        GET /v1/cryptocurrency/listings/latest
        Returns top `limit` cryptocurrencies sorted by market cap,
        with quotes in both USD and IRR.
        """
        params = {
            "limit": limit,
            "convert": "USD",
            "sort": "market_cap",
            "sort_dir": "desc",
        }
        data = self._get("/v1/cryptocurrency/listings/latest", params=params)
        # data is a list of coin objects
        return data if isinstance(data, list) else []

    def fetch_global_metrics(self) -> dict:
        """
        GET /v1/global-metrics/quotes/latest
        Returns global crypto market metrics (total market cap, volume, dominance).
        """
        params = {"convert": "USD"}
        return self._get("/v1/global-metrics/quotes/latest", params=params)


# ---------------------------------------------------------------------------
# Module-level client instance
# ---------------------------------------------------------------------------

_cmc = CMCClient()


# ---------------------------------------------------------------------------
# CMC English symbol → Farsi DB symbol mapping
# ---------------------------------------------------------------------------

from config.crypto_symbols import CMC_TO_FA as _CMC_TO_FA


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------


def _get_crypto_security_map(session) -> dict[str, int]:
    """
    Query the securities table and return a mapping of
    {Farsi_symbol: security_id} for all active crypto coins.
    """
    stmt = select(Security.symbol, Security.security_id, Security.name_en).where(
        Security.market_type == "crypto",
        Security.is_active.is_(True),
    )
    rows = session.execute(stmt).all()
    fa_to_id = {row.symbol: row.security_id for row in rows}
    # Also index by name_en (English symbol) for reverse lookup
    en_to_id = {row.name_en: row.security_id for row in rows if row.name_en}
    return fa_to_id, en_to_id


def _resolve_security_id(session, cmc_symbol: str, cmc_name: str,
                          fa_to_id: dict, en_to_id: dict) -> int | None:
    """
    Resolve a CMC coin to a security_id. Lookup order:
    1. _CMC_TO_FA mapping → search by Farsi symbol
    2. name_en field → search by English symbol
    3. Auto-create a new security record
    """
    # 1. Check known mapping
    fa_sym = _CMC_TO_FA.get(cmc_symbol)
    if fa_sym and fa_sym in fa_to_id:
        return fa_to_id[fa_sym]

    # 2. Check by English symbol stored in name_en
    if cmc_symbol in en_to_id:
        return en_to_id[cmc_symbol]

    # 3. Auto-create — use Persian name from mapping, else English name
    display_name = fa_sym or cmc_name or cmc_symbol
    new_sec = Security(
        symbol=display_name,
        name_fa=display_name,
        name_en=cmc_symbol,
        market_type="crypto",
        is_active=True,
    )
    session.add(new_sec)
    session.flush()
    fa_to_id[display_name] = new_sec.security_id
    en_to_id[cmc_symbol] = new_sec.security_id
    logger.info(f"Auto-created crypto security: {cmc_symbol} ({cmc_name}) → {display_name} (id={new_sec.security_id})")
    return new_sec.security_id


# ---------------------------------------------------------------------------
# Core data-fetching and storage functions
# ---------------------------------------------------------------------------


def fetch_and_store_tickers(session) -> int:
    """
    Fetch top 30 listings from CoinMarketCap, map to tracked securities,
    and bulk-insert CryptoTicker rows.

    CMC provides USD + IRR quotes in a single call (no Wallex needed).
    Returns the number of ticker rows inserted.
    """
    fa_to_id, en_to_id = _get_crypto_security_map(session)

    listings = _cmc.fetch_listings(limit=200)
    if not listings:
        logger.warning("CMC returned no listings")
        return 0

    now = datetime.now(UTC)
    rows = []

    for coin in listings:
        symbol = coin.get("symbol", "")
        cmc_name = coin.get("name", symbol)
        security_id = _resolve_security_id(session, symbol, cmc_name, fa_to_id, en_to_id)
        if security_id is None:
            continue

        usd_quote = coin.get("quote", {}).get("USD", {})
        irr_quote = coin.get("quote", {}).get("IRR", {})

        last_price = usd_quote.get("price")
        if last_price is not None:
            last_price = Decimal(str(last_price))

        pct_24h = usd_quote.get("percent_change_24h")
        price_change_24h = None
        if last_price and pct_24h is not None:
            price_change_24h = last_price * Decimal(str(pct_24h)) / Decimal("100")

        volume_24h = usd_quote.get("volume_24h")
        market_cap = usd_quote.get("market_cap")

        # IRR price from CMC's built-in conversion
        price_toman = None
        irr_price = irr_quote.get("price")
        if irr_price is not None:
            price_toman = Decimal(str(irr_price))

        rows.append(
            {
                "security_id": security_id,
                "snapshot_time": now,
                "last_price": last_price,
                "price_change_24h": price_change_24h,
                "price_change_pct_24h": (
                    Decimal(str(pct_24h)) if pct_24h is not None else None
                ),
                "high_24h": None,  # CMC listings don't include 24h high/low
                "low_24h": None,
                "volume_24h": (
                    Decimal(str(volume_24h)) if volume_24h is not None else None
                ),
                "turnover_24h": (
                    Decimal(str(volume_24h)) if volume_24h is not None else None
                ),
                "best_bid": None,  # CMC doesn't provide bid/ask
                "best_ask": None,
                "market_cap_usd": (
                    Decimal(str(market_cap)) if market_cap is not None else None
                ),
                "price_toman": price_toman,
            }
        )

    if not rows:
        logger.warning("No matching crypto securities for CMC listings")
        return 0

    # Bulk insert
    session.execute(CryptoTicker.__table__.insert(), rows)
    session.flush()

    logger.info(f"Inserted {len(rows)} crypto ticker snapshots")

    # Publish live update via Redis pub/sub
    _publish_crypto_update(
        {
            "event": "crypto_ticker",
            "count": len(rows),
            "timestamp": now.isoformat(),
        }
    )

    return len(rows)


def generate_daily_ohlcv_from_tickers(session) -> int:
    """
    Generate daily OHLCV candles by aggregating CryptoTicker snapshots.
    For each tracked crypto, aggregate yesterday's ticker snapshots into:
      open  = first snapshot's last_price
      close = last snapshot's last_price
      high  = max(last_price)
      low   = min(last_price)
      volume = last snapshot's volume_24h (cumulative from CMC)

    Upserts via INSERT ... ON CONFLICT DO UPDATE.
    Returns the total number of rows upserted.
    """
    fa_to_id, en_to_id = _get_crypto_security_map(session)
    # Collect all unique security_ids
    all_sec_ids = set(fa_to_id.values()) | set(en_to_id.values())
    if not all_sec_ids:
        logger.warning("No crypto securities found; skipping OHLCV generation")
        return 0

    # Aggregate yesterday's ticker snapshots
    yesterday = date.today() - timedelta(days=1)
    day_start = datetime(yesterday.year, yesterday.month, yesterday.day, tzinfo=UTC)
    day_end = day_start + timedelta(days=1)

    interval = "1day"
    total_upserted = 0

    for security_id in all_sec_ids:
        # Get aggregated stats for yesterday
        agg_stmt = select(
            func.min(CryptoTicker.last_price).label("low"),
            func.max(CryptoTicker.last_price).label("high"),
            func.count(CryptoTicker.id).label("cnt"),
        ).where(
            CryptoTicker.security_id == security_id,
            CryptoTicker.snapshot_time >= day_start,
            CryptoTicker.snapshot_time < day_end,
            CryptoTicker.last_price.isnot(None),
        )
        agg = session.execute(agg_stmt).first()

        if not agg or agg.cnt == 0:
            continue

        # Get first snapshot (open price)
        first_stmt = (
            select(CryptoTicker.last_price)
            .where(
                CryptoTicker.security_id == security_id,
                CryptoTicker.snapshot_time >= day_start,
                CryptoTicker.snapshot_time < day_end,
                CryptoTicker.last_price.isnot(None),
            )
            .order_by(CryptoTicker.snapshot_time.asc())
            .limit(1)
        )
        open_price = session.execute(first_stmt).scalar()

        # Get last snapshot (close price + volume)
        last_stmt = (
            select(CryptoTicker.last_price, CryptoTicker.volume_24h)
            .where(
                CryptoTicker.security_id == security_id,
                CryptoTicker.snapshot_time >= day_start,
                CryptoTicker.snapshot_time < day_end,
                CryptoTicker.last_price.isnot(None),
            )
            .order_by(CryptoTicker.snapshot_time.desc())
            .limit(1)
        )
        last_row = session.execute(last_stmt).first()

        if open_price is None or last_row is None:
            continue

        row = {
            "security_id": security_id,
            "interval": interval,
            "open_time": day_start,
            "open": open_price,
            "high": agg.high,
            "low": agg.low,
            "close": last_row.last_price,
            "volume": last_row.volume_24h,
            "turnover": last_row.volume_24h,
        }

        stmt = insert(CryptoOHLCV).values(row)
        stmt = stmt.on_conflict_do_update(
            constraint="uq_crypto_ohlcv_sec_interval_time",
            set_={
                "open": stmt.excluded.open,
                "high": stmt.excluded.high,
                "low": stmt.excluded.low,
                "close": stmt.excluded.close,
                "volume": stmt.excluded.volume,
                "turnover": stmt.excluded.turnover,
            },
        )
        session.execute(stmt)
        session.flush()
        total_upserted += 1
        logger.debug(f"Upserted daily OHLCV candle for {symbol}")

    logger.info(f"Daily OHLCV generation complete: {total_upserted} rows upserted")
    return total_upserted


def fetch_and_store_global_metrics(session) -> dict:
    """
    Fetch global crypto market metrics from CoinMarketCap
    and the Fear & Greed index from alternative.me, then upsert into
    the CryptoGlobalMetrics table (one row per day).

    Returns a dict summarizing the fetched data.
    """
    result = {}
    today = date.today()

    # ── CMC global metrics ──
    try:
        cmc_data = _cmc.fetch_global_metrics()
        usd_quote = cmc_data.get("quote", {}).get("USD", {})

        result["total_market_cap_usd"] = usd_quote.get("total_market_cap")
        result["total_volume_24h_usd"] = usd_quote.get("total_volume_24h")
        result["btc_dominance_pct"] = cmc_data.get("btc_dominance")
        result["eth_dominance_pct"] = cmc_data.get("eth_dominance")
        result["active_coins"] = cmc_data.get("active_cryptocurrencies")
    except Exception as e:
        logger.error(f"Failed to fetch CMC global metrics: {e}")

    # ── Fear & Greed Index (free public API, no CMC credits) ──
    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.get(FEAR_GREED_URL, params={"limit": 1})
            resp.raise_for_status()
            fg_data = resp.json().get("data", [])

        if fg_data:
            result["fear_greed_value"] = int(fg_data[0].get("value", 0))
            result["fear_greed_label"] = fg_data[0].get("value_classification", "")
    except Exception as e:
        logger.error(f"Failed to fetch Fear & Greed index: {e}")

    if not result:
        logger.warning("No global metrics fetched; skipping upsert")
        return result

    # ── Upsert into CryptoGlobalMetrics ──
    row = {"date": today}
    if result.get("total_market_cap_usd") is not None:
        row["total_market_cap_usd"] = Decimal(str(result["total_market_cap_usd"]))
    if result.get("total_volume_24h_usd") is not None:
        row["total_volume_24h_usd"] = Decimal(str(result["total_volume_24h_usd"]))
    if result.get("btc_dominance_pct") is not None:
        row["btc_dominance_pct"] = Decimal(str(round(result["btc_dominance_pct"], 2)))
    if result.get("eth_dominance_pct") is not None:
        row["eth_dominance_pct"] = Decimal(str(round(result["eth_dominance_pct"], 2)))
    if result.get("active_coins") is not None:
        row["active_coins"] = result["active_coins"]
    if result.get("fear_greed_value") is not None:
        row["fear_greed_value"] = result["fear_greed_value"]
    if result.get("fear_greed_label") is not None:
        row["fear_greed_label"] = result["fear_greed_label"]

    stmt = insert(CryptoGlobalMetrics).values(row)
    update_cols = {k: v for k, v in row.items() if k != "date"}
    stmt = stmt.on_conflict_do_update(
        index_elements=["date"],
        set_=update_cols,
    )
    session.execute(stmt)
    session.flush()

    logger.info(f"Upserted global crypto metrics for {today}")
    return result


def cleanup_old_tickers(
    session, retention_hours: int = CRYPTO_TICKER_RETENTION_HOURS
) -> int:
    """
    Delete CryptoTicker rows older than `retention_hours`.
    Returns the number of rows deleted.
    """
    cutoff = datetime.now(UTC) - timedelta(hours=retention_hours)
    deleted = (
        session.query(CryptoTicker)
        .filter(CryptoTicker.snapshot_time < cutoff)
        .delete(synchronize_session=False)
    )
    session.flush()
    logger.info(
        f"Deleted {deleted} old crypto ticker snapshots (retention={retention_hours}h)"
    )
    return deleted


def _publish_crypto_update(data: dict) -> None:
    """
    Publish a crypto data update to Redis pub/sub on the
    `tse:live:crypto` channel.
    """
    try:
        from api.cache import cache_manager

        if cache_manager.available:
            cache_manager._client.publish(
                REDIS_CHANNEL_CRYPTO,
                json.dumps(data, default=str),
            )
    except Exception as e:
        logger.debug(f"Redis publish error (crypto): {e}")
