import {
  IconFlame,
  IconChartTreemap,
  IconScale,
  IconStar,
  IconChartLine,
  IconDroplet,
  IconDiamond,
  IconPlant,
  IconBarrel,
  IconAtom,
  IconMeat,
  IconCoffee,
  IconGrain,
} from '@tabler/icons-react';

export const commodityMenuSections = [
  {
    label: 'بازار کالا',
    items: [
      { text: 'داشبورد', icon: IconFlame, path: '/commodity' },
      { text: 'نقشه بازار', icon: IconChartTreemap, path: '/commodity/heatmap' },
      { text: 'مقایسه', icon: IconScale, path: '/commodity/compare' },
      { text: 'دیده‌بان', icon: IconStar, path: '/commodity/watchlist' },
      { text: 'نمودار قیمت', icon: IconChartLine, path: '/commodity/charts' },
    ],
  },
  {
    label: 'انرژی',
    items: [
      { text: 'نفت خام WTI', icon: IconBarrel, path: '/commodity/WTI' },
      { text: 'نفت برنت', icon: IconBarrel, path: '/commodity/BRENT' },
      { text: 'گاز طبیعی', icon: IconDroplet, path: '/commodity/NATGAS' },
      { text: 'بنزین', icon: IconDroplet, path: '/commodity/GASOLINE' },
      { text: 'نفت گرمایشی', icon: IconDroplet, path: '/commodity/HEAT' },
      { text: 'اورانیوم', icon: IconAtom, path: '/commodity/URANIUM' },
      { text: 'پروپان', icon: IconDroplet, path: '/commodity/PROPANE' },
      { text: 'گاز TTF اروپا', icon: IconDroplet, path: '/commodity/TTF_GAS' },
    ],
  },
  {
    label: 'فلزات',
    items: [
      { text: 'طلا', icon: IconDiamond, path: '/commodity/GOLD' },
      { text: 'نقره', icon: IconDiamond, path: '/commodity/SILVER' },
      { text: 'مس', icon: IconAtom, path: '/commodity/COPPER' },
      { text: 'پلاتین', icon: IconDiamond, path: '/commodity/PLATINUM' },
      { text: 'پالادیوم', icon: IconDiamond, path: '/commodity/PALLADIUM' },
      { text: 'آلومینیوم', icon: IconAtom, path: '/commodity/ALUMINUM' },
      { text: 'سنگ‌آهن', icon: IconAtom, path: '/commodity/IRON_ORE' },
      { text: 'فولاد نورد گرم', icon: IconAtom, path: '/commodity/HRC_STEEL' },
      { text: 'روی', icon: IconAtom, path: '/commodity/ZINC' },
      { text: 'نیکل', icon: IconAtom, path: '/commodity/NICKEL' },
      { text: 'سرب', icon: IconAtom, path: '/commodity/LEAD' },
      { text: 'قلع', icon: IconAtom, path: '/commodity/TIN' },
      { text: 'لیتیوم', icon: IconAtom, path: '/commodity/LITHIUM' },
      { text: 'کبالت', icon: IconAtom, path: '/commodity/COBALT' },
    ],
  },
  {
    label: 'کشاورزی',
    items: [
      { text: 'ذرت', icon: IconGrain, path: '/commodity/CORN' },
      { text: 'گندم', icon: IconGrain, path: '/commodity/WHEAT' },
      { text: 'سویا', icon: IconPlant, path: '/commodity/SOYBEAN' },
      { text: 'برنج', icon: IconGrain, path: '/commodity/RICE' },
      { text: 'جو دوسر', icon: IconGrain, path: '/commodity/OATS' },
      { text: 'کانولا', icon: IconPlant, path: '/commodity/CANOLA' },
      { text: 'قهوه', icon: IconCoffee, path: '/commodity/COFFEE' },
      { text: 'شکر', icon: IconPlant, path: '/commodity/SUGAR' },
      { text: 'کاکائو', icon: IconCoffee, path: '/commodity/COCOA' },
      { text: 'پنبه', icon: IconPlant, path: '/commodity/COTTON' },
      { text: 'آب پرتقال', icon: IconDroplet, path: '/commodity/OJ' },
      { text: 'الوار', icon: IconPlant, path: '/commodity/LUMBER' },
      { text: 'شیر', icon: IconDroplet, path: '/commodity/MILK' },
      { text: 'پنیر', icon: IconDroplet, path: '/commodity/CHEESE' },
    ],
  },
  {
    label: 'دام',
    items: [
      { text: 'گاو زنده', icon: IconMeat, path: '/commodity/CATTLE' },
      { text: 'گاو پرواری', icon: IconMeat, path: '/commodity/FEEDER' },
      { text: 'خوک', icon: IconMeat, path: '/commodity/HOGS' },
    ],
  },
];
