import {
  IconBuildingBank,
  IconCalculator,
  IconChartBar,
  IconChartLine,
  IconCoin,
} from '@tabler/icons-react';
import rallyColors from '../theme/rallyColors';

/**
 * Shared templates used by both ModelSidebar and ModelEmptyState.
 * Each entry can serve as a sidebar template button or an empty-state quick-start card.
 */
export const TEMPLATES = [
  {
    label: 'ارزش‌گذاری DCF',
    shortLabel: 'مدل DCF',
    icon: IconChartLine,
    color: rallyColors.green,
    prompt: 'یک مدل DCF برای شرکتی با EBIT ۵۰۰ میلیارد ریال، WACC 22% و نرخ رشد پایانه 3% بساز',
  },
  {
    label: 'پیش‌بینی P&L',
    shortLabel: 'صورت سود و زیان',
    icon: IconCalculator,
    color: rallyColors.blue,
    prompt: 'پیش‌بینی P&L برای ۳ سال با درآمد پایه ۱۰۰۰ میلیارد ریال و رشد ۱۵٪',
  },
  {
    label: 'WACC و CAPM',
    shortLabel: 'WACC و CAPM',
    icon: IconChartBar,
    color: '#14B8A6',
    prompt: 'محاسبه WACC برای شرکتی با بتای ۱.۲، نرخ بدون ریسک ۲۰٪، صرف ریسک بازار ۶٪، نسبت بدهی ۳۰٪ و نرخ بهره ۱۸٪',
  },
  {
    label: 'مدل DDM',
    shortLabel: 'مدل DDM',
    icon: IconCoin,
    color: '#06B6D4',
    prompt: 'ارزش‌گذاری سهام با سود سهام پایه ۵۰۰ ریال، نرخ رشد ۸٪ و نرخ تنزیل ۱۵٪ با مدل گوردون',
  },
  {
    label: 'جدول اقساط',
    shortLabel: 'جدول اقساط',
    icon: IconBuildingBank,
    color: rallyColors.purple,
    prompt: 'جدول استهلاک وام ۵۰۰ میلیون ریالی با نرخ ۱۸٪ سالانه و مدت ۳۶ ماه',
  },
  {
    label: 'DCF کامل از پایه',
    shortLabel: 'DCF کامل از پایه',
    icon: IconChartLine,
    color: '#6366F1',
    prompt: 'یک DCF کامل برای شرکتی با درآمد پایه ۱۰۰۰ میلیارد ریال بساز: ابتدا مدل درآمد با رشد ۱۵٪ برای ۳ سال، سپس سرمایه در گردش با DSO=30، DIO=45، DPO=20 و COGS=60٪، سپس DCF با WACC=22٪',
  },
  {
    label: 'مدل سه‌گانه IS+BS+CF',
    shortLabel: 'مدل سه‌گانه IS+BS+CF',
    icon: IconChartLine,
    color: '#0D9488',
    prompt: 'صورت‌های مالی سه‌گانه برای شرکتی با EBIT 200 میلیارد ریال، وام 400 میلیارد با نرخ ۱۸٪، CapEx 80 میلیارد و D&A 50 میلیارد بساز',
  },
  {
    label: 'Beta + WACC + DCF',
    shortLabel: 'Beta + WACC + DCF',
    icon: IconChartBar,
    color: '#64748B',
    prompt: 'برای شرکتی با بتای مشاهده‌شده ۱.۵ و D/E=۰.۸ و نرخ مالیات ۲۵٪، ابتدا بتا را با معادله هامادا غیراهرم کن، سپس WACC با نرخ بدون ریسک ۲۰٪ و صرف ریسک ۶٪ محاسبه کن',
  },
  {
    label: 'ارزش‌گذاری IB سهام',
    shortLabel: 'IB Valuation',
    icon: IconChartLine,
    color: rallyColors.red,
    prompt: 'یک مدل ارزش‌گذاری IB کامل ۱۰ شیتی برای اپل (AAPL) بساز با ۵ سال تاریخی و ۵ سال پیش‌بینی',
  },
];

/**
 * Maps financial-modeling tool names → model_type identifiers.
 * Used by ModelChatArea to detect which model card to render.
 */
export const FM_TOOL_TO_TYPE = {
  build_dcf_model: 'dcf',
  build_pl_model: 'pl',
  build_loan_amortization: 'loan_amortization',
  build_bond_model: 'bond',
  build_ddm_model: 'ddm_gordon',
  build_residual_income_model: 'residual_income',
  build_multiples_model: 'multiples',
  compute_wacc: 'wacc',
  compute_capm: 'capm',
  compute_fcfe: 'fcfe',
  build_revenue_model: 'revenue_model',
  build_wc_model: 'wc_model',
  build_capex_schedule: 'capex_schedule',
  build_debt_schedule: 'debt_schedule',
  build_three_statement_model: 'three_statement',
  compute_beta: 'beta',
  build_scenario_model: 'scenario_model',
  compute_operating_leverage: 'operating_leverage',
  compute_pvgo: 'pvgo',
  compute_eva: 'eva',
  // Phase 5
  build_lbo_model: 'lbo',
  build_ma_model: 'ma',
  compute_credit_metrics: 'credit_metrics',
  compute_liquidation_value: 'liquidation',
  compute_ipo_pricing: 'ipo',
  compute_altman_z: 'altman_z',
  compute_beneish_score: 'beneish',
  compute_accrual_ratios: 'accrual_ratios',
  compute_variance_analysis: 'variance_analysis',
  // Phase 6
  compute_portfolio_stats: 'portfolio_stats',
  compute_risk_metrics: 'risk_metrics',
  compute_var: 'var',
  compute_cvar: 'cvar',
  run_monte_carlo: 'monte_carlo',
  optimize_portfolio: 'portfolio_optimization',
  compute_efficient_frontier: 'efficient_frontier',
  compute_risk_parity: 'risk_parity',
  compute_factor_model: 'factor_model',
  run_stress_test: 'stress_test',
  // Phase 7
  price_option_bsm: 'bsm',
  price_option_binomial: 'binomial_tree',
  compute_greeks: 'greeks',
  compute_implied_volatility: 'implied_volatility',
  check_put_call_parity: 'put_call_parity',
  build_option_strategy: 'option_strategy',
  // Phase 8
  compute_real_estate_noi: 'real_estate_noi',
  build_development_proforma: 'development_proforma',
  build_sukuk_model: 'sukuk',
  build_murabaha_schedule: 'murabaha',
  build_ijara_model: 'ijara',
  compute_inflation_adjusted_valuation: 'inflation_adjusted',
  build_tehran_housing_model: 'tehran_housing',
  // Phase 10
  compute_dupont: 'dupont',
  compute_brinson_attribution: 'brinson',
  compute_black_litterman: 'black_litterman',
  compute_pe_fund_metrics: 'pe_fund',
  compute_omega_ratio: 'omega_ratio',
  compute_credit_risk: 'credit_risk',
  compute_forward_rates: 'forward_rates',
  build_equity_valuation_model: 'equity_valuation',
};

/**
 * Friendly tool-name labels for badge display (Persian).
 */
export const FM_TOOL_LABELS = {
  build_dcf_model: 'DCF',
  build_pl_model: 'P&L',
  build_loan_amortization: 'اقساط',
  build_bond_model: 'اوراق',
  build_ddm_model: 'DDM',
  build_residual_income_model: 'RI',
  build_multiples_model: 'ضرایب',
  compute_wacc: 'WACC',
  compute_capm: 'CAPM',
  compute_fcfe: 'FCFE',
  build_revenue_model: 'درآمد',
  build_wc_model: 'سرمایه در گردش',
  build_capex_schedule: 'CapEx',
  build_debt_schedule: 'بدهی',
  build_three_statement_model: 'سه‌گانه',
  compute_beta: 'بتا',
  build_scenario_model: 'سناریو',
  compute_operating_leverage: 'اهرم',
  compute_pvgo: 'PVGO',
  compute_eva: 'EVA',
  build_lbo_model: 'LBO',
  build_ma_model: 'M&A',
  compute_credit_metrics: 'اعتباری',
  compute_liquidation_value: 'تسویه',
  compute_ipo_pricing: 'IPO',
  compute_altman_z: 'Altman Z',
  compute_beneish_score: 'Beneish',
  compute_accrual_ratios: 'تعهدی',
  compute_variance_analysis: 'واریانس',
  compute_portfolio_stats: 'پرتفوی',
  compute_risk_metrics: 'ریسک',
  compute_var: 'VaR',
  compute_cvar: 'CVaR',
  run_monte_carlo: 'مونت‌کارلو',
  optimize_portfolio: 'بهینه‌سازی',
  compute_efficient_frontier: 'مرز کارا',
  compute_risk_parity: 'ریسک‌پریتی',
  compute_factor_model: 'فاکتور',
  run_stress_test: 'استرس‌تست',
  price_option_bsm: 'BSM',
  price_option_binomial: 'دوجمله‌ای',
  compute_greeks: 'یونانی‌ها',
  compute_implied_volatility: 'IV',
  check_put_call_parity: 'پوت-کال',
  build_option_strategy: 'استراتژی',
  compute_real_estate_noi: 'NOI',
  build_development_proforma: 'پروفرما',
  build_sukuk_model: 'صکوک',
  build_murabaha_schedule: 'مرابحه',
  build_ijara_model: 'اجاره',
  compute_inflation_adjusted_valuation: 'تورم',
  build_tehran_housing_model: 'مسکن',
  compute_dupont: 'DuPont',
  compute_brinson_attribution: 'Brinson',
  compute_black_litterman: 'BL',
  compute_pe_fund_metrics: 'PE Fund',
  compute_omega_ratio: 'Omega',
  compute_credit_risk: 'ریسک اعتباری',
  compute_forward_rates: 'نرخ آتی',
  build_equity_valuation_model: 'ارزش‌گذاری IB سهام',
};

/** Metadata per model type: display label, badge color, key metrics to show. */
export const MODEL_META = {
  dcf: { label: 'ارزش‌گذاری DCF', color: 'teal', metrics: ['enterprise_value', 'equity_value', 'price_per_share', 'wacc_pct'] },
  pl: { label: 'سود و زیان', color: 'blue', metrics: [] },
  loan_amortization: { label: 'جدول اقساط', color: 'violet', metrics: [] },
  bond: { label: 'اوراق بدهی', color: 'orange', metrics: ['price', 'ytm_pct', 'macaulay_duration_years', 'modified_duration'] },
  ddm_gordon: { label: 'DDM گوردون', color: 'cyan', metrics: ['intrinsic_value', 'discount_rate_pct', 'growth_rate_pct'] },
  ddm_h_model: { label: 'DDM مدل H', color: 'cyan', metrics: ['intrinsic_value', 'discount_rate_pct'] },
  ddm_multistage: { label: 'DDM چندمرحله‌ای', color: 'cyan', metrics: ['intrinsic_value', 'pv_dividends', 'pv_terminal'] },
  residual_income: { label: 'درآمد باقیمانده', color: 'grape', metrics: ['intrinsic_value', 'premium_to_book', 'pv_explicit_ri', 'pv_continuing_ri'] },
  multiples: { label: 'ضرایب قیمتی', color: 'yellow', metrics: ['implied_price_min', 'implied_price_median', 'implied_price_max'] },
  wacc: { label: 'WACC', color: 'teal', metrics: ['wacc_pct', 'equity_weight', 'debt_weight', 'after_tax_cost_of_debt_pct'] },
  capm: { label: 'CAPM', color: 'teal', metrics: ['cost_of_equity_pct', 'beta', 'risk_free_rate_pct', 'equity_risk_premium_pct'] },
  fcfe: { label: 'FCFE', color: 'indigo', metrics: ['fcfe'] },
  revenue_model: { label: 'مدل درآمد', color: 'green', metrics: ['total_revenue'] },
  wc_model: { label: 'سرمایه در گردش', color: 'blue', metrics: ['ccc'] },
  capex_schedule: { label: 'برنامه CapEx', color: 'orange', metrics: [] },
  debt_schedule: { label: 'برنامه بدهی', color: 'red', metrics: [] },
  three_statement: { label: 'صورت‌های مالی سه‌گانه', color: 'teal', metrics: [] },
  beta: { label: 'بتا (هامادا)', color: 'gray', metrics: ['unlevered_beta', 're_levered_beta', 'adjusted_beta'] },
  scenario_model: { label: 'تحلیل سناریو', color: 'yellow', metrics: [] },
  operating_leverage: { label: 'اهرم عملیاتی', color: 'orange', metrics: ['dol', 'breakeven_revenue', 'cm_ratio'] },
  pvgo: { label: 'PVGO', color: 'cyan', metrics: ['pvgo', 'pvgo_pct_of_value', 'justified_pe_leading'] },
  eva: { label: 'EVA', color: 'green', metrics: ['eva', 'roic_pct', 'eva_spread_pct'] },
  bsm: { label: 'بلک-شولز', color: 'pink', metrics: ['price', 'd1', 'd2', 'time_value'] },
  binomial_tree: { label: 'درخت دوجمله‌ای', color: 'pink', metrics: ['price', 'u', 'd', 'p'] },
  greeks: { label: 'یونانی‌ها', color: 'pink', metrics: ['delta', 'gamma', 'vega', 'theta'] },
  implied_volatility: { label: 'نوسان ضمنی', color: 'pink', metrics: ['implied_volatility'] },
  put_call_parity: { label: 'برابری پوت-کال', color: 'pink', metrics: ['deviation', 'arbitrage_opportunity'] },
  option_strategy: { label: 'استراتژی اختیار', color: 'pink', metrics: ['max_profit', 'max_loss'] },
  equity_valuation: { label: 'ارزش‌گذاری IB سهام', color: 'red', metrics: ['implied_price_dcf_gordon', 'implied_price_dcf_exit', 'implied_price_blended', 'wacc_pct', 'upside_pct', 'recommendation'] },
};

/** Persian labels for individual metric keys. */
export const METRIC_LABELS = {
  enterprise_value: 'ارزش سازمان (EV)',
  equity_value: 'ارزش حقوق صاحبان',
  price_per_share: 'ارزش هر سهم (ریال)',
  wacc_pct: 'WACC (%)',
  price: 'قیمت اوراق',
  ytm_pct: 'YTM (%)',
  macaulay_duration_years: 'دیرش مکالی',
  modified_duration: 'دیرش اصلاح‌شده',
  intrinsic_value: 'ارزش ذاتی',
  discount_rate_pct: 'نرخ تنزیل (%)',
  growth_rate_pct: 'نرخ رشد (%)',
  pv_dividends: 'PV سود سهام',
  pv_terminal: 'PV ارزش پایانه',
  premium_to_book: 'صرف به ارزش دفتری',
  pv_explicit_ri: 'PV RI صریح',
  pv_continuing_ri: 'PV RI ادامه',
  implied_price_min: 'قیمت کمینه ضمنی',
  implied_price_median: 'قیمت میانه ضمنی',
  implied_price_max: 'قیمت بیشینه ضمنی',
  equity_weight: 'وزن حقوق صاحبان',
  debt_weight: 'وزن بدهی',
  after_tax_cost_of_debt_pct: 'هزینه بدهی پس از مالیات (%)',
  cost_of_equity_pct: 'هزینه حقوق صاحبان (%)',
  risk_free_rate_pct: 'نرخ بدون ریسک (%)',
  equity_risk_premium_pct: 'صرف ریسک بازار (%)',
  beta: 'بتا',
  fcfe: 'FCFE',
  total_revenue: 'کل درآمد',
  ccc: 'چرخه تبدیل نقد (روز)',
  unlevered_beta: 'بتای غیراهرمی',
  re_levered_beta: 'بتای اهرم‌شده',
  adjusted_beta: 'بتای تعدیل‌شده',
  dol: 'اهرم عملیاتی (DOL)',
  breakeven_revenue: 'درآمد سربه‌سر',
  cm_ratio: 'نسبت حاشیه مشارکت',
  pvgo_pct_of_value: 'PVGO (٪ ارزش)',
  justified_pe_leading: 'P/E توجیه‌پذیر پیشرو',
  roic_pct: 'ROIC (%)',
  eva_spread_pct: 'اسپرد EVA (%)',
  d1: 'd1',
  d2: 'd2',
  time_value: 'ارزش زمانی',
  u: 'ضریب صعود (u)',
  d: 'ضریب نزول (d)',
  p: 'احتمال ریسک‌خنثی (p)',
  delta: 'دلتا (Δ)',
  gamma: 'گاما (Γ)',
  vega: 'وگا (ν)',
  theta: 'تتا (Θ)',
  implied_volatility: 'نوسان ضمنی',
  deviation: 'انحراف',
  arbitrage_opportunity: 'فرصت آربیتراژ',
  max_profit: 'حداکثر سود',
  max_loss: 'حداکثر زیان',
  implied_price_dcf_gordon: 'قیمت ضمنی DCF (گوردون)',
  implied_price_dcf_exit: 'قیمت ضمنی DCF (خروج)',
  implied_price_blended: 'قیمت ضمنی ترکیبی',
  upside_pct: 'پتانسیل رشد (%)',
  recommendation: 'توصیه',
  model_checks_passed: 'بررسی‌های موفق',
  model_checks_total: 'کل بررسی‌ها',
};
