import {
  IconTrendingUp,
  IconBuildingBank,
  IconBriefcase,
  IconCoin,
  IconChartLine,
  IconChartBar,
  IconReceipt,
  IconShieldCheck,
  IconDiamond,
  IconChartArea,
  IconChartPie,
  IconCurrencyDollar,
  IconDatabase,
  IconChartAreaLine,
  IconQuote,
  IconRobot,
} from '@tabler/icons-react';

export const FEATURES = [
  {
    title: 'بازار ایران',
    subtitle: 'بورس اوراق بهادار تهران',
    description: 'داده‌های لحظه‌ای سهام، شاخص‌ها، نقشه بازار و تحلیل جامع بازار سرمایه',
    icon: IconTrendingUp,
    accent: '#10B981',
    accentName: 'green',
    route: '/dashboard',
    bullets: [
      { icon: IconChartLine, text: 'نمودار شمعی و تحلیل تکنیکال' },
      { icon: IconChartBar, text: 'نقشه گرمایی و فیلتر پیشرفته' },
      { icon: IconCoin, text: 'حقیقی-حقوقی و جریان نقدینگی' },
    ],
  },
  {
    title: 'تسهیلات بانکی',
    subtitle: 'مقایسه و محاسبه وام',
    description: 'بررسی و مقایسه انواع تسهیلات بانکی با محاسبه دقیق اقساط',
    icon: IconBuildingBank,
    accent: '#8B5CF6',
    accentName: 'purple',
    route: '/loans',
    bullets: [
      { icon: IconReceipt, text: 'محاسبه اقساط و سود تسهیلات' },
      { icon: IconShieldCheck, text: 'مقایسه شرایط بانک‌ها' },
      { icon: IconDiamond, text: 'پیشنهاد هوشمند بر اساس پروفایل' },
    ],
  },
  {
    title: 'پورتفولیو',
    subtitle: 'مدیریت سبد سهام',
    description: 'ثبت دارایی‌ها، پایش ارزش لحظه‌ای، تحلیل ریسک و بازده سبد سرمایه‌گذاری',
    icon: IconBriefcase,
    accent: '#3B82F6',
    accentName: 'blue',
    route: '/portfolio',
    bullets: [
      { icon: IconChartArea, text: 'ارزش‌گذاری لحظه‌ای سبد' },
      { icon: IconShieldCheck, text: 'تحلیل ریسک: بتا، نوسان‌پذیری، VaR' },
      { icon: IconChartPie, text: 'تخصیص دارایی و مقایسه با شاخص' },
    ],
  },
  {
    title: 'رمزارزها',
    subtitle: 'بازار ارزهای دیجیتال',
    description: 'پایش لحظه‌ای ۳۰ رمزارز برتر، نمودار قیمت، مقایسه و تحلیل بازار کریپتو',
    icon: IconCoin,
    accent: '#F59E0B',
    accentName: 'yellow',
    route: '/crypto',
    bullets: [
      { icon: IconCurrencyDollar, text: 'قیمت لحظه‌ای به دلار و تومان' },
      { icon: IconChartLine, text: 'نمودار شمعی و نقشه گرمایی' },
      { icon: IconChartBar, text: 'شاخص ترس و طمع و سلطه بیت‌کوین' },
    ],
  },
];

export const STATS = [
  { icon: IconDatabase, value: 1200, suffix: '+', label: 'نماد و صندوق' },
  { icon: IconChartAreaLine, value: 40, suffix: '+', label: 'صفحه تحلیلی' },
  { icon: IconCoin, value: 30, suffix: '+', label: 'رمزارز' },
  { icon: IconBuildingBank, value: 6, suffix: '', label: 'بازار تحت پوشش' },
  { icon: IconRobot, value: 19, suffix: '', label: 'ابزار هوش مصنوعی' },
];

export const PRICING_PLANS = [
  {
    name: 'رایگان',
    price: 'رایگان',
    period: '',
    accent: '#10B981',
    featured: false,
    features: [
      { text: 'داشبورد بورس تهران', included: true },
      { text: 'رمزارزها', included: true },
      { text: 'تسهیلات بانکی', included: true },
      { text: 'پرتفوی و مدیریت سبد', included: false },
      { text: 'دستیار هوشمند (چت‌بات AI)', included: false },
      { text: 'تحلیل تکنیکال پیشرفته', included: false },
    ],
    cta: 'ورود رایگان',
    route: '/dashboard',
    disabled: false,
  },
  {
    name: 'حرفه‌ای',
    price: '۲۹۹,۰۰۰',
    period: 'تومان/ماه',
    accent: '#10B981',
    featured: true,
    features: [
      { text: 'داشبورد بورس تهران', included: true },
      { text: 'رمزارزها', included: true },
      { text: 'تسهیلات بانکی', included: true },
      { text: 'پرتفوی و مدیریت سبد', included: true },
      { text: 'دستیار هوشمند (چت‌بات AI)', included: true },
      { text: 'تحلیل تکنیکال پیشرفته', included: true },
      { text: 'داده‌های بورس کالا', included: true },
      { text: 'API اختصاصی', included: false },
    ],
    cta: 'شروع دوره آزمایشی',
    route: null,
    disabled: true,
  },
  {
    name: 'سازمانی',
    price: 'تماس بگیرید',
    period: '',
    accent: '#8B5CF6',
    featured: false,
    features: [
      { text: 'داشبورد بورس تهران', included: true },
      { text: 'رمزارزها', included: true },
      { text: 'تسهیلات بانکی', included: true },
      { text: 'پرتفوی و مدیریت سبد', included: true },
      { text: 'دستیار هوشمند (چت‌بات AI)', included: true },
      { text: 'تحلیل تکنیکال پیشرفته', included: true },
      { text: 'داده‌های بورس کالا', included: true },
      { text: 'API اختصاصی', included: true },
      { text: 'پشتیبانی اختصاصی', included: true },
      { text: 'گزارش‌های سفارشی', included: true },
    ],
    cta: 'تماس با ما',
    route: null,
    disabled: true,
  },
];

export const TESTIMONIALS = [
  {
    name: 'محمد رضایی',
    role: 'تحلیلگر بنیادی',
    text: 'بهترین داشبورد بورسی که تا حالا دیدم. نقشه بازار و فیلتر پیشرفته کارم رو خیلی سریع‌تر کرده.',
    avatar: 'م',
  },
  {
    name: 'سارا احمدی',
    role: 'مدیر پورتفولیو',
    text: 'تحلیل ریسک و محاسبه شارپ ریشو به صورت لحظه‌ای واقعا عالیه. دیگه نیازی به اکسل ندارم.',
    avatar: 'س',
  },
  {
    name: 'علی حسینی',
    role: 'معامله‌گر رمزارز',
    text: 'قیمت تومانی رمزارزها و شاخص ترس و طمع رو همیشه از اینجا چک می‌کنم. خیلی دقیق و به‌روز.',
    avatar: 'ع',
  },
  {
    name: 'فاطمه کریمی',
    role: 'مشاور مالی',
    text: 'ماشین حساب مالی وام‌ها با محاسبه IRR و NPV یک ابزار حرفه‌ای واقعیه.',
    avatar: 'ف',
  },
];
