"""
CMC (CoinMarketCap) English ticker ↔ Farsi display name mappings.

Used by the crypto router to translate between the API's English symbols
and the Farsi symbols stored in the Security table.

Coins not in this mapping are handled dynamically:
- The fetcher stores them with name_en as the symbol
- The API returns name_en (English) when no Farsi name exists
"""

CMC_TO_FA: dict[str, str] = {
    # Top 50 by market cap — manually verified Persian names
    "BTC": "بیت‌کوین",
    "ETH": "اتریوم",
    "USDT": "تتر",
    "XRP": "ریپل",
    "BNB": "بایننس کوین",
    "SOL": "سولانا",
    "USDC": "یو‌اس‌دی‌سی",
    "TRX": "ترون",
    "DOGE": "دوج‌کوین",
    "ADA": "کاردانو",
    "LINK": "چین‌لینک",
    "AVAX": "آوالانچ",
    "XLM": "استلار",
    "SHIB": "شیبا اینو",
    "TON": "تون‌کوین",
    "DOT": "پولکادات",
    "HBAR": "هدرا هش‌گراف",
    "BCH": "بیت‌کوین کش",
    "LTC": "لایت‌کوین",
    "UNI": "یونی‌سواپ",
    "NEAR": "نیر پروتکل",
    "APT": "آپتوس",
    "PEPE": "پپه",
    "ICP": "اینترنت کامپیوتر",
    "ETC": "اتریوم کلاسیک",
    "AAVE": "آوه",
    "RENDER": "رندر توکن",
    "FET": "فچ ای‌آی",
    "XMR": "مونرو",
    "ARB": "آربیتروم",
    "OP": "آپتیمیزم",
    "FIL": "فایل‌کوین",
    "ATOM": "کازموس",
    "INJ": "اینجکتیو",
    "TIA": "سلستیا",
    "BONK": "بونک",
    "WLD": "ورلدکوین",
    "APE": "ایپ‌کوین",
    "OM": "مانترا دائو",
    "POL": "پالیگان اکوسیستم توکن",
    # 51–100
    "VET": "وی‌چین",
    "ALGO": "الگوراند",
    "GRT": "دِ گراف",
    "FTM": "فانتوم",
    "SAND": "سندباکس",
    "MANA": "دیسنترالند",
    "THETA": "تتا",
    "AXS": "اکسی اینفینیتی",
    "FLOW": "فلو",
    "EGLD": "مالتی‌ورس‌ایکس",
    "EOS": "ای‌او‌اس",
    "GALA": "گالا",
    "CHZ": "چیلیز",
    "CRV": "کرو",
    "SNX": "سینتتیکس",
    "LDO": "لیدو",
    "COMP": "کامپاوند",
    "MKR": "میکر",
    "QNT": "کوانت",
    "RUNE": "تورچین",
    "ENS": "ای‌ان‌اس",
    "RPL": "راکت پول",
    "DYDX": "دی‌وای‌دی‌ایکس",
    "IOTA": "آیوتا",
    "NEO": "نئو",
    "ZEC": "زی‌کش",
    "KCS": "کوکوین",
    "KAVA": "کاوا",
    "ONE": "هارمونی",
    "GMX": "جی‌ام‌ایکس",
    "CFX": "کانفلاکس",
    "DASH": "دش",
    "ZIL": "زیلیقا",
    "ENJ": "انجین",
    "BAT": "بیسیک اتنشن توکن",
    "1INCH": "وان‌اینچ",
    "CELO": "سلو",
    "ROSE": "اُیسیس",
    "SKL": "اسکیل",
    "JASMY": "جاسمی",
    "MASK": "مسک نتورک",
    "BLUR": "بلور",
    "SSV": "اس‌اس‌وی",
    "PENDLE": "پندل",
    "JUP": "جوپیتر",
    "PYTH": "پایث",
    "SEI": "سِی",
    "SUI": "سوئی",
    "TAO": "بیت‌تنسور",
    "STX": "استکس",
    "ONDO": "اوندو",
    "W": "ورم‌هول",
    "STRK": "استارک‌نت",
    "ZRO": "لیرزیرو",
    "ETHFI": "اتر فای",
    "ENA": "اتنا",
    "NOT": "نات‌کوین",
    "FLOKI": "فلوکی",
}

FA_TO_CMC: dict[str, str] = {v: k for k, v in CMC_TO_FA.items()}
