-- Creates the streaming replication user.
-- Runs automatically on first DB initialisation (docker-entrypoint-initdb.d).
-- The password is overridden by POSTGRES_REPLICATION_PASSWORD in docker-compose.yml
-- via the replica entrypoint; keeping a default here ensures the user exists even
-- in bare `docker run` scenarios.
-- Replication user is created by docker-entrypoint-initdb.d/00-replication-setup.sh
-- using the POSTGRES_REPLICATION_PASSWORD environment variable.
