"""
Comprehensive Bank Data Update Script
Updates all banks with detailed loan information
"""

import asyncio
from motor.motor_asyncio import AsyncIOMotorClient

MONGODB_URL = "mongodb://admin:securepassword123@localhost:27017"
DATABASE_NAME = "iranian_banks"

# Complete bank data with all details
BANKS_DATA = [
    # ===================== DIGITAL BANKS =====================
    {
        "id": "sepino",
        "nameFA": "سپینو",
        "nameEN": "Sepino",
        "category": "digital-banks",
        "type": "neobank",
        "parentBank": "Bank Saderat Iran",
        "parentBankFA": "بانک صادرات ایران",
        "website": "https://sepino.ir",
        "appDownload": "https://cafebazaar.ir/app/ir.bsi.sepino",
        "description": "Sepino is the digital banking arm of Bank Saderat, offering fully online loan services without branch visits",
        "descriptionFA": "سپینو شعبه دیجیتال بانک صادرات است که خدمات تسهیلات کاملاً آنلاین بدون نیاز به مراجعه حضوری ارائه می‌دهد",
        "calculationMethod": "deposit-based",
        "loanTypes": [
            {
                "id": "nitro",
                "nameFA": "وام نیترو",
                "nameEN": "Nitro Loan",
                "category": "deposit-based",
                "categoryFA": "وام بر اساس سپرده",
                "minAmount": "5,000,000",
                "maxAmount": "600,000,000",
                "minAmountNumeric": 5000000,
                "maxAmountNumeric": 600000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "6 ماه",
                "maxTerm": "36 ماه",
                "guarantor": False,
                "description": "Loan based on deposit average, up to 4x your deposit",
                "descriptionFA": "وام بر اساس میانگین سپرده، تا ۴ برابر موجودی حساب",
                "requirements": ["حساب فعال در سپینو", "حداقل یک ماه سپرده‌گذاری", "رتبه اعتباری مناسب"],
                "processingTime": "۲۴ ساعت"
            },
            {
                "id": "no-guarantor",
                "nameFA": "تسهیلات بدون ضامن",
                "nameEN": "No Guarantor Loan",
                "category": "instant",
                "categoryFA": "وام فوری",
                "minAmount": "10,000,000",
                "maxAmount": "100,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 100000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "48 ماه",
                "guarantor": False,
                "description": "Quick loan without guarantor for customers with good credit",
                "descriptionFA": "وام سریع بدون ضامن برای مشتریان با رتبه اعتباری خوب",
                "requirements": ["حقوق از طریق بانک صادرات یا رتبه اعتباری A", "سفته الکترونیک", "بدون چک برگشتی"],
                "processingTime": "فوری"
            },
            {
                "id": "sana-2",
                "nameFA": "طرح سنا ۲",
                "nameEN": "Sana 2 Plan",
                "category": "savings-based",
                "categoryFA": "بر اساس پس‌انداز",
                "maxAmount": "300,000,000",
                "maxAmountNumeric": 300000000,
                "interestRate": "15-23%",
                "minTerm": "18 ماه",
                "maxTerm": "60 ماه",
                "guarantor": False,
                "description": "Lower interest rate for longer savings periods",
                "descriptionFA": "نرخ سود کمتر برای دوره‌های پس‌انداز طولانی‌تر",
                "requirements": ["افتتاح حساب سپرده کوتاه‌مدت سنا", "حداقل ۲ ماه میانگین حساب"],
                "processingTime": "۴۸ ساعت"
            },
            {
                "id": "murabaha-card",
                "nameFA": "کارت اعتباری مرابحه",
                "nameEN": "Murabaha Credit Card",
                "category": "credit-card",
                "categoryFA": "کارت اعتباری",
                "maxAmount": "200,000,000",
                "maxAmountNumeric": 200000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": False,
                "description": "Revolving credit card for purchases",
                "descriptionFA": "کارت اعتباری گردشی برای خرید کالا و خدمات",
                "requirements": ["اعتبارسنجی آنلاین", "سفته الکترونیک"],
                "processingTime": "۷۲ ساعت"
            },
            {
                "id": "star-sepino",
                "nameFA": "طرح ستاره سپینو",
                "nameEN": "Star Sepino BNPL",
                "category": "bnpl",
                "categoryFA": "خرید اقساطی",
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": False,
                "description": "Buy now pay later from partner stores",
                "descriptionFA": "خرید اقساطی از فروشگاه‌های طرف قرارداد",
                "requirements": ["خرید از فروشگاه‌های طرف قرارداد"],
                "processingTime": "فوری"
            }
        ],
        "generalRequirements": {
            "guarantor": False,
            "digitalPromissoryNote": True,
            "onlineCreditCheck": True,
            "minAge": 18,
            "maxAge": 70,
            "noBadChecks": True,
            "noOverdueDebts": True
        },
        "features": ["سفته الکترونیک", "اعتبارسنجی آنلاین", "افتتاح حساب آنلاین", "ارسال رایگان کارت"],
        "loansCount": 5,
        "lastUpdated": "2026-02-02"
    },
    {
        "id": "qbank",
        "nameFA": "کیوبانک",
        "nameEN": "Qbank",
        "category": "digital-banks",
        "type": "neobank",
        "parentBank": "Bank Ayandeh",
        "parentBankFA": "بانک آینده",
        "website": "https://qbank.ir",
        "appDownload": "https://cafebazaar.ir/app/ir.qbank",
        "description": "Qbank is a digital bank by Bank Ayandeh focusing on innovative loan products",
        "descriptionFA": "کیوبانک بانک دیجیتال بانک آینده با تمرکز بر محصولات تسهیلاتی نوآورانه",
        "calculationMethod": "average-based",
        "loanTypes": [
            {
                "id": "vam-fori",
                "nameFA": "وام فوری",
                "nameEN": "Instant Loan",
                "category": "instant",
                "categoryFA": "وام فوری",
                "minAmount": "5,000,000",
                "maxAmount": "50,000,000",
                "minAmountNumeric": 5000000,
                "maxAmountNumeric": 50000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "6 ماه",
                "maxTerm": "24 ماه",
                "guarantor": False,
                "description": "Quick loan based on account activity",
                "descriptionFA": "وام سریع بر اساس فعالیت حساب",
                "requirements": ["حساب فعال کیوبانک", "رتبه اعتباری مناسب"],
                "processingTime": "فوری"
            },
            {
                "id": "vam-miangin",
                "nameFA": "وام میانگین",
                "nameEN": "Average-Based Loan",
                "category": "average-based",
                "categoryFA": "بر اساس میانگین",
                "minAmount": "10,000,000",
                "maxAmount": "200,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 200000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": False,
                "description": "Loan up to 3x account average",
                "descriptionFA": "وام تا ۳ برابر میانگین حساب",
                "requirements": ["حداقل ۳ ماه میانگین حساب", "گردش منظم حساب"],
                "processingTime": "۲۴ ساعت"
            },
            {
                "id": "kharid-eghsati",
                "nameFA": "خرید اقساطی",
                "nameEN": "Installment Purchase",
                "category": "bnpl",
                "categoryFA": "خرید اقساطی",
                "maxAmount": "100,000,000",
                "maxAmountNumeric": 100000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "6 ماه",
                "maxTerm": "24 ماه",
                "guarantor": False,
                "description": "Buy from partner merchants in installments",
                "descriptionFA": "خرید از فروشگاه‌های طرف قرارداد به صورت اقساطی",
                "processingTime": "فوری"
            },
            {
                "id": "cart-etebari",
                "nameFA": "کارت اعتباری",
                "nameEN": "Credit Card",
                "category": "credit-card",
                "categoryFA": "کارت اعتباری",
                "maxAmount": "150,000,000",
                "maxAmountNumeric": 150000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": False,
                "description": "Digital credit card with instant approval",
                "descriptionFA": "کارت اعتباری دیجیتال با تأیید فوری",
                "processingTime": "۴۸ ساعت"
            },
            {
                "id": "vam-zaroorat",
                "nameFA": "وام ضرورت",
                "nameEN": "Emergency Loan",
                "category": "emergency",
                "categoryFA": "وام ضروری",
                "minAmount": "2,000,000",
                "maxAmount": "20,000,000",
                "minAmountNumeric": 2000000,
                "maxAmountNumeric": 20000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "3 ماه",
                "maxTerm": "12 ماه",
                "guarantor": False,
                "description": "Small emergency loan for immediate needs",
                "descriptionFA": "وام کوچک ضروری برای نیازهای فوری",
                "processingTime": "فوری"
            },
            {
                "id": "vam-vizheh",
                "nameFA": "وام ویژه",
                "nameEN": "Special Loan",
                "category": "premium",
                "categoryFA": "وام ویژه",
                "minAmount": "50,000,000",
                "maxAmount": "500,000,000",
                "minAmountNumeric": 50000000,
                "maxAmountNumeric": 500000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "24 ماه",
                "maxTerm": "60 ماه",
                "guarantor": True,
                "description": "Large loan for premium customers",
                "descriptionFA": "وام بزرگ برای مشتریان ویژه",
                "requirements": ["حداقل ۶ ماه سابقه حساب", "ضامن معتبر", "رتبه اعتباری عالی"],
                "processingTime": "۷۲ ساعت"
            }
        ],
        "generalRequirements": {
            "guarantor": False,
            "digitalPromissoryNote": True,
            "onlineCreditCheck": True,
            "minAge": 18,
            "maxAge": 65,
            "noBadChecks": True
        },
        "features": ["وام بدون ضامن", "تأیید فوری", "اعتبارسنجی آنلاین", "اپلیکیشن موبایل"],
        "loansCount": 6,
        "lastUpdated": "2026-02-02"
    },
    {
        "id": "bankino",
        "nameFA": "بانکینو",
        "nameEN": "Bankino",
        "category": "digital-banks",
        "type": "neobank",
        "parentBank": "EN Bank",
        "parentBankFA": "بانک اقتصاد نوین",
        "website": "https://bankino.ir",
        "appDownload": "https://cafebazaar.ir/app/ir.enbank.bankino",
        "description": "Bankino offers point-based loan system where you earn points through account activity",
        "descriptionFA": "بانکینو سیستم وام امتیازی ارائه می‌دهد که با فعالیت حساب امتیاز کسب می‌کنید",
        "calculationMethod": "points-based",
        "loanTypes": [
            {
                "id": "vam-emtiazi",
                "nameFA": "وام امتیازی",
                "nameEN": "Points-Based Loan",
                "category": "points-based",
                "categoryFA": "وام امتیازی",
                "minAmount": "5,000,000",
                "maxAmount": "300,000,000",
                "minAmountNumeric": 5000000,
                "maxAmountNumeric": 300000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "48 ماه",
                "guarantor": False,
                "description": "Loan amount based on accumulated points",
                "descriptionFA": "مبلغ وام بر اساس امتیاز جمع‌آوری شده",
                "requirements": ["جمع‌آوری امتیاز از طریق تراکنش‌ها", "حداقل ۱۰۰۰ امتیاز"],
                "processingTime": "۲۴ ساعت"
            },
            {
                "id": "vam-fori-bankino",
                "nameFA": "وام فوری بانکینو",
                "nameEN": "Bankino Instant Loan",
                "category": "instant",
                "categoryFA": "وام فوری",
                "minAmount": "2,000,000",
                "maxAmount": "50,000,000",
                "minAmountNumeric": 2000000,
                "maxAmountNumeric": 50000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "6 ماه",
                "maxTerm": "24 ماه",
                "guarantor": False,
                "description": "Quick instant loan for urgent needs",
                "descriptionFA": "وام فوری برای نیازهای ضروری",
                "requirements": ["حساب فعال بانکینو", "رتبه اعتباری مناسب"],
                "processingTime": "فوری"
            }
        ],
        "scoringSystem": {
            "description": "Earn points through transactions, deposits, and account activity",
            "descriptionFA": "از طریق تراکنش‌ها، سپرده‌گذاری و فعالیت حساب امتیاز کسب کنید",
            "pointPurchase": True,
            "pointTransfer": True,
            "maxPoints": 100000
        },
        "generalRequirements": {
            "guarantor": False,
            "digitalPromissoryNote": True,
            "onlineCreditCheck": True,
            "minAge": 18,
            "maxAge": 65
        },
        "features": ["سیستم امتیازی", "خرید و انتقال امتیاز", "وام بدون ضامن"],
        "loansCount": 2,
        "lastUpdated": "2026-02-02"
    },
    {
        "id": "weepod",
        "nameFA": "ویپاد",
        "nameEN": "Weepod",
        "category": "digital-banks",
        "type": "neobank",
        "parentBank": "Bank Pasargad",
        "parentBankFA": "بانک پاسارگاد",
        "website": "https://weepod.ir",
        "appDownload": "https://cafebazaar.ir/app/ir.weepod",
        "description": "Weepod by Bank Pasargad offers step-based loan system with increasing limits",
        "descriptionFA": "ویپاد بانک پاسارگاد سیستم وام پلکانی با افزایش تدریجی سقف ارائه می‌دهد",
        "calculationMethod": "step-based",
        "loanTypes": [
            {
                "id": "vam-pellekani",
                "nameFA": "وام پلکانی",
                "nameEN": "Step Loan",
                "category": "step-based",
                "categoryFA": "وام پلکانی",
                "minAmount": "5,000,000",
                "maxAmount": "500,000,000",
                "minAmountNumeric": 5000000,
                "maxAmountNumeric": 500000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "60 ماه",
                "guarantor": False,
                "description": "Loan limit increases with each successful repayment",
                "descriptionFA": "سقف وام با هر بازپرداخت موفق افزایش می‌یابد",
                "requirements": ["شروع از وام کوچک", "بازپرداخت به‌موقع"],
                "processingTime": "۲۴ ساعت"
            },
            {
                "id": "vam-fori-weepod",
                "nameFA": "وام فوری ویپاد",
                "nameEN": "Weepod Instant Loan",
                "category": "instant",
                "categoryFA": "وام فوری",
                "minAmount": "2,000,000",
                "maxAmount": "30,000,000",
                "minAmountNumeric": 2000000,
                "maxAmountNumeric": 30000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "3 ماه",
                "maxTerm": "12 ماه",
                "guarantor": False,
                "description": "Quick loan for verified users",
                "descriptionFA": "وام سریع برای کاربران تأیید شده",
                "processingTime": "فوری"
            },
            {
                "id": "kharid-eghsati-weepod",
                "nameFA": "خرید اقساطی ویپاد",
                "nameEN": "Weepod BNPL",
                "category": "bnpl",
                "categoryFA": "خرید اقساطی",
                "maxAmount": "100,000,000",
                "maxAmountNumeric": 100000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "6 ماه",
                "maxTerm": "24 ماه",
                "guarantor": False,
                "description": "Installment purchase from partner stores",
                "descriptionFA": "خرید اقساطی از فروشگاه‌های طرف قرارداد",
                "processingTime": "فوری"
            },
            {
                "id": "cart-etebari-weepod",
                "nameFA": "کارت اعتباری ویپاد",
                "nameEN": "Weepod Credit Card",
                "category": "credit-card",
                "categoryFA": "کارت اعتباری",
                "maxAmount": "200,000,000",
                "maxAmountNumeric": 200000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": False,
                "description": "Digital credit card with flexible limits",
                "descriptionFA": "کارت اعتباری دیجیتال با سقف منعطف",
                "processingTime": "۴۸ ساعت"
            }
        ],
        "generalRequirements": {
            "guarantor": False,
            "digitalPromissoryNote": True,
            "onlineCreditCheck": True,
            "minAge": 18,
            "maxAge": 65
        },
        "features": ["وام پلکانی", "افزایش سقف با بازپرداخت", "وام بدون ضامن", "کارت اعتباری دیجیتال"],
        "loansCount": 4,
        "lastUpdated": "2026-02-02"
    },
    {
        "id": "blu-bank",
        "nameFA": "بلوبانک",
        "nameEN": "Blu Bank",
        "category": "digital-banks",
        "type": "neobank",
        "parentBank": "Saman Bank",
        "parentBankFA": "بانک سامان",
        "website": "https://blubank.ir",
        "appDownload": "https://cafebazaar.ir/app/ir.blubank",
        "description": "Blu Bank by Saman Bank offers modern digital banking with average-based loans",
        "descriptionFA": "بلوبانک بانک سامان خدمات بانکداری دیجیتال مدرن با وام بر اساس میانگین ارائه می‌دهد",
        "calculationMethod": "average-based",
        "loanTypes": [
            {
                "id": "vam-blu",
                "nameFA": "وام بلو",
                "nameEN": "Blu Loan",
                "category": "average-based",
                "categoryFA": "بر اساس میانگین",
                "minAmount": "5,000,000",
                "maxAmount": "300,000,000",
                "minAmountNumeric": 5000000,
                "maxAmountNumeric": 300000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "48 ماه",
                "guarantor": False,
                "description": "Loan based on account average balance",
                "descriptionFA": "وام بر اساس میانگین موجودی حساب",
                "requirements": ["حداقل ۳ ماه میانگین حساب", "گردش منظم"],
                "processingTime": "۲۴ ساعت"
            },
            {
                "id": "vam-fori-blu",
                "nameFA": "وام فوری بلو",
                "nameEN": "Blu Instant Loan",
                "category": "instant",
                "categoryFA": "وام فوری",
                "minAmount": "2,000,000",
                "maxAmount": "50,000,000",
                "minAmountNumeric": 2000000,
                "maxAmountNumeric": 50000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "6 ماه",
                "maxTerm": "24 ماه",
                "guarantor": False,
                "description": "Quick approval instant loan",
                "descriptionFA": "وام فوری با تأیید سریع",
                "processingTime": "فوری"
            },
            {
                "id": "cart-etebari-blu",
                "nameFA": "کارت اعتباری بلو",
                "nameEN": "Blu Credit Card",
                "category": "credit-card",
                "categoryFA": "کارت اعتباری",
                "maxAmount": "200,000,000",
                "maxAmountNumeric": 200000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": False,
                "description": "Digital credit card with modern features",
                "descriptionFA": "کارت اعتباری دیجیتال با امکانات مدرن",
                "processingTime": "۴۸ ساعت"
            }
        ],
        "generalRequirements": {
            "guarantor": False,
            "digitalPromissoryNote": True,
            "onlineCreditCheck": True,
            "minAge": 18,
            "maxAge": 65
        },
        "features": ["رابط کاربری مدرن", "وام بدون ضامن", "کارت اعتباری دیجیتال"],
        "loansCount": 3,
        "lastUpdated": "2026-02-02"
    },
    {
        "id": "neshan-bank",
        "nameFA": "نشان بانک",
        "nameEN": "Neshan Bank",
        "category": "digital-banks",
        "type": "neobank",
        "website": "https://neshanbank.ir",
        "appDownload": "https://cafebazaar.ir/app/ir.neshanbank",
        "description": "Neshan Bank offers collateral-based digital loans with competitive rates",
        "descriptionFA": "نشان بانک وام‌های دیجیتال با پشتوانه دارایی با نرخ رقابتی ارائه می‌دهد",
        "calculationMethod": "collateral-based",
        "loanTypes": [
            {
                "id": "vam-rahni",
                "nameFA": "وام رهنی",
                "nameEN": "Collateral Loan",
                "category": "collateral-based",
                "categoryFA": "وام رهنی",
                "minAmount": "50,000,000",
                "maxAmount": "2,000,000,000",
                "minAmountNumeric": 50000000,
                "maxAmountNumeric": 2000000000,
                "interestRate": "18-23%",
                "minTerm": "24 ماه",
                "maxTerm": "120 ماه",
                "guarantor": False,
                "description": "Large loan secured by property collateral",
                "descriptionFA": "وام بزرگ با پشتوانه ملک",
                "requirements": ["سند ملک", "ارزیابی ملک", "بیمه ملک"],
                "processingTime": "۷ روز کاری"
            },
            {
                "id": "vam-khodro",
                "nameFA": "وام خودرو",
                "nameEN": "Auto Loan",
                "category": "auto",
                "categoryFA": "وام خودرو",
                "minAmount": "50,000,000",
                "maxAmount": "500,000,000",
                "minAmountNumeric": 50000000,
                "maxAmountNumeric": 500000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "60 ماه",
                "guarantor": False,
                "description": "Loan for vehicle purchase with vehicle as collateral",
                "descriptionFA": "وام خرید خودرو با وثیقه خودرو",
                "requirements": ["سند خودرو", "بیمه بدنه"],
                "processingTime": "۳ روز کاری"
            },
            {
                "id": "vam-tala",
                "nameFA": "وام طلا",
                "nameEN": "Gold-Backed Loan",
                "category": "gold-backed",
                "categoryFA": "وام طلا",
                "minAmount": "10,000,000",
                "maxAmount": "500,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 500000000,
                "interestRate": "18%",
                "interestRateNumeric": 18,
                "minTerm": "6 ماه",
                "maxTerm": "24 ماه",
                "guarantor": False,
                "description": "Loan secured by gold deposit",
                "descriptionFA": "وام با پشتوانه سپرده طلا",
                "requirements": ["سپرده طلا در بانک"],
                "processingTime": "۲۴ ساعت"
            }
        ],
        "generalRequirements": {
            "guarantor": False,
            "collateralRequired": True,
            "onlineCreditCheck": True,
            "minAge": 18,
            "maxAge": 70
        },
        "features": ["وام با پشتوانه دارایی", "نرخ رقابتی", "سقف بالا"],
        "loansCount": 3,
        "lastUpdated": "2026-02-02"
    },
    {
        "id": "hi-bank",
        "nameFA": "های بانک",
        "nameEN": "Hi Bank",
        "category": "digital-banks",
        "type": "neobank",
        "website": "https://hibank.ir",
        "appDownload": "https://cafebazaar.ir/app/ir.hibank",
        "description": "Hi Bank offers step-based lending with gamified experience",
        "descriptionFA": "های بانک وام پلکانی با تجربه گیمیفای شده ارائه می‌دهد",
        "calculationMethod": "step-based",
        "loanTypes": [
            {
                "id": "vam-starter",
                "nameFA": "وام استارتر",
                "nameEN": "Starter Loan",
                "category": "step-based",
                "categoryFA": "وام شروع",
                "minAmount": "2,000,000",
                "maxAmount": "20,000,000",
                "minAmountNumeric": 2000000,
                "maxAmountNumeric": 20000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "3 ماه",
                "maxTerm": "12 ماه",
                "guarantor": False,
                "description": "First step loan for new users",
                "descriptionFA": "اولین قدم وام برای کاربران جدید",
                "requirements": ["ثبت‌نام در های بانک", "احراز هویت"],
                "processingTime": "فوری"
            },
            {
                "id": "vam-pro",
                "nameFA": "وام پرو",
                "nameEN": "Pro Loan",
                "category": "step-based",
                "categoryFA": "وام حرفه‌ای",
                "minAmount": "20,000,000",
                "maxAmount": "100,000,000",
                "minAmountNumeric": 20000000,
                "maxAmountNumeric": 100000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": False,
                "description": "Second level loan after successful starter repayment",
                "descriptionFA": "سطح دوم وام پس از بازپرداخت موفق استارتر",
                "requirements": ["بازپرداخت موفق وام استارتر", "رتبه اعتباری خوب"],
                "processingTime": "۲۴ ساعت"
            },
            {
                "id": "vam-elite",
                "nameFA": "وام الیت",
                "nameEN": "Elite Loan",
                "category": "step-based",
                "categoryFA": "وام ویژه",
                "minAmount": "100,000,000",
                "maxAmount": "500,000,000",
                "minAmountNumeric": 100000000,
                "maxAmountNumeric": 500000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "24 ماه",
                "maxTerm": "60 ماه",
                "guarantor": True,
                "description": "Premium loan for trusted customers",
                "descriptionFA": "وام ویژه برای مشتریان قابل اعتماد",
                "requirements": ["سابقه بازپرداخت عالی", "ضامن معتبر"],
                "processingTime": "۴۸ ساعت"
            }
        ],
        "generalRequirements": {
            "guarantor": False,
            "digitalPromissoryNote": True,
            "onlineCreditCheck": True,
            "minAge": 18,
            "maxAge": 60
        },
        "features": ["سیستم پلکانی", "گیمیفیکیشن", "افزایش سقف با اعتماد"],
        "loansCount": 3,
        "lastUpdated": "2026-02-02"
    },

    # ===================== TRADITIONAL BANKS =====================
    {
        "id": "bank-meli",
        "nameFA": "بانک ملی ایران",
        "nameEN": "Bank Meli Iran",
        "category": "traditional-banks",
        "type": "state-owned",
        "website": "https://bmi.ir",
        "description": "Bank Meli Iran is the largest and oldest state-owned commercial bank in Iran",
        "descriptionFA": "بانک ملی ایران بزرگترین و قدیمی‌ترین بانک تجاری دولتی ایران است",
        "loanTypes": [
            {
                "id": "mehrabani",
                "nameFA": "طرح مهربانی ملی",
                "nameEN": "Mehrabani Plan",
                "category": "zero-interest",
                "categoryFA": "قرض‌الحسنه",
                "minAmount": "10,000,000",
                "maxAmount": "200,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 200000000,
                "interestRate": "0%",
                "interestRateNumeric": 0,
                "fee": "4%",
                "minTerm": "12 ماه",
                "maxTerm": "60 ماه",
                "guarantor": True,
                "description": "Zero interest loan with small fee",
                "descriptionFA": "وام بدون سود با کارمزد کم",
                "requirements": ["ضامن معتبر", "میانگین حساب ۱-۱۲ ماه"],
                "processingTime": "۳-۵ روز کاری"
            },
            {
                "id": "kargoshaei",
                "nameFA": "طرح کارگشای ملی",
                "nameEN": "Kargoshaei Plan",
                "category": "business",
                "categoryFA": "تسهیلات کسب و کار",
                "minAmount": "50,000,000",
                "maxAmount": "1,000,000,000",
                "minAmountNumeric": 50000000,
                "maxAmountNumeric": 1000000000,
                "interestRate": "18%",
                "interestRateNumeric": 18,
                "minTerm": "12 ماه",
                "maxTerm": "60 ماه",
                "guarantor": True,
                "description": "Business facilitation loan for SMEs",
                "descriptionFA": "تسهیلات تسهیل کسب و کار برای شرکت‌های کوچک و متوسط",
                "requirements": ["مجوز کسب و کار", "صورت‌های مالی", "ضامن یا وثیقه"],
                "processingTime": "۷-۱۴ روز کاری"
            },
            {
                "id": "etebar-meli",
                "nameFA": "طرح اعتبار ملی",
                "nameEN": "Etebar Meli Plan",
                "category": "credit-based",
                "categoryFA": "بر اساس اعتبار",
                "minAmount": "20,000,000",
                "maxAmount": "500,000,000",
                "minAmountNumeric": 20000000,
                "maxAmountNumeric": 500000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "48 ماه",
                "guarantor": True,
                "description": "Loan based on credit rating and deposit ratio",
                "descriptionFA": "وام بر اساس رتبه اعتباری و نسبت سپرده",
                "requirements": ["رتبه اعتباری مناسب", "میانگین حساب", "ضامن"],
                "processingTime": "۳-۵ روز کاری"
            },
            {
                "id": "paziraneh",
                "nameFA": "وام پذیرنده ملی",
                "nameEN": "Paziraneh Plan",
                "category": "pos-owners",
                "categoryFA": "دارندگان کارتخوان",
                "minAmount": "20,000,000",
                "maxAmount": "300,000,000",
                "minAmountNumeric": 20000000,
                "maxAmountNumeric": 300000000,
                "interestRate": "18%",
                "interestRateNumeric": 18,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": False,
                "description": "Special loan for POS terminal owners based on transaction volume",
                "descriptionFA": "وام ویژه دارندگان کارتخوان بر اساس حجم تراکنش",
                "requirements": ["کارتخوان فعال بانک ملی", "گردش مالی منظم"],
                "processingTime": "۲-۳ روز کاری"
            },
            {
                "id": "tasahilat-tarjihi",
                "nameFA": "تسهیلات نرخ ترجیحی",
                "nameEN": "Preferential Rate Loan",
                "category": "preferential",
                "categoryFA": "نرخ ترجیحی",
                "minAmount": "50,000,000",
                "maxAmount": "2,000,000,000",
                "minAmountNumeric": 50000000,
                "maxAmountNumeric": 2000000000,
                "interestRate": "15%",
                "interestRateNumeric": 15,
                "minTerm": "24 ماه",
                "maxTerm": "120 ماه",
                "guarantor": True,
                "description": "Lower interest rate for specific sectors",
                "descriptionFA": "نرخ سود کمتر برای بخش‌های خاص اقتصادی",
                "requirements": ["فعالیت در بخش‌های اولویت‌دار", "ضمانت‌نامه یا وثیقه"],
                "processingTime": "۱۴-۲۱ روز کاری"
            }
        ],
        "generalRequirements": {
            "creditRating": True,
            "accountAverage": True,
            "guarantor": True,
            "minAge": 18,
            "maxAge": 75
        },
        "features": ["بزرگترین شبکه شعب", "تنوع محصولات", "خدمات ارزی"],
        "loansCount": 5,
        "lastUpdated": "2026-02-02"
    },
    {
        "id": "bank-saderat",
        "nameFA": "بانک صادرات ایران",
        "nameEN": "Bank Saderat Iran",
        "category": "traditional-banks",
        "type": "public",
        "website": "https://bsi.ir",
        "description": "Bank Saderat Iran is one of the largest banks in Iran with extensive retail and corporate services",
        "descriptionFA": "بانک صادرات ایران یکی از بزرگترین بانک‌های ایران با خدمات گسترده خرد و شرکتی است",
        "loanTypes": [
            {
                "id": "vam-mehr",
                "nameFA": "وام مهر صادرات",
                "nameEN": "Mehr Loan",
                "category": "zero-interest",
                "categoryFA": "قرض‌الحسنه",
                "minAmount": "10,000,000",
                "maxAmount": "150,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 150000000,
                "interestRate": "0%",
                "interestRateNumeric": 0,
                "fee": "4%",
                "minTerm": "12 ماه",
                "maxTerm": "48 ماه",
                "guarantor": True,
                "description": "Zero interest welfare loan",
                "descriptionFA": "وام رفاهی بدون سود",
                "requirements": ["ضامن کارمند", "چک یا سفته"],
                "processingTime": "۳-۷ روز کاری"
            },
            {
                "id": "vam-foori-saderat",
                "nameFA": "وام فوری صادرات",
                "nameEN": "Saderat Quick Loan",
                "category": "quick",
                "categoryFA": "وام سریع",
                "minAmount": "10,000,000",
                "maxAmount": "100,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 100000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": True,
                "description": "Quick processing loan",
                "descriptionFA": "وام با پردازش سریع",
                "requirements": ["حساب فعال", "ضامن"],
                "processingTime": "۲-۳ روز کاری"
            },
            {
                "id": "vam-maskan",
                "nameFA": "وام مسکن",
                "nameEN": "Housing Loan",
                "category": "housing",
                "categoryFA": "وام مسکن",
                "minAmount": "500,000,000",
                "maxAmount": "4,000,000,000",
                "minAmountNumeric": 500000000,
                "maxAmountNumeric": 4000000000,
                "interestRate": "18%",
                "interestRateNumeric": 18,
                "minTerm": "60 ماه",
                "maxTerm": "240 ماه",
                "guarantor": False,
                "collateral": True,
                "description": "Home purchase loan with property collateral",
                "descriptionFA": "وام خرید مسکن با وثیقه ملکی",
                "requirements": ["سند ملک", "ارزیابی", "بیمه"],
                "processingTime": "۱۴-۳۰ روز کاری"
            },
            {
                "id": "vam-khodro-saderat",
                "nameFA": "وام خودرو صادرات",
                "nameEN": "Saderat Auto Loan",
                "category": "auto",
                "categoryFA": "وام خودرو",
                "minAmount": "100,000,000",
                "maxAmount": "700,000,000",
                "minAmountNumeric": 100000000,
                "maxAmountNumeric": 700000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "60 ماه",
                "guarantor": False,
                "collateral": True,
                "description": "Auto purchase loan",
                "descriptionFA": "وام خرید خودرو",
                "requirements": ["پیش‌پرداخت ۳۰٪", "بیمه بدنه"],
                "processingTime": "۵-۷ روز کاری"
            },
            {
                "id": "vam-jari",
                "nameFA": "وام جاری",
                "nameEN": "Current Account Loan",
                "category": "overdraft",
                "categoryFA": "اعتبار جاری",
                "minAmount": "20,000,000",
                "maxAmount": "500,000,000",
                "minAmountNumeric": 20000000,
                "maxAmountNumeric": 500000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "12 ماه",
                "guarantor": True,
                "description": "Revolving credit line",
                "descriptionFA": "اعتبار گردشی در حساب جاری",
                "requirements": ["حساب جاری فعال", "چک", "ضامن"],
                "processingTime": "۳-۵ روز کاری"
            },
            {
                "id": "sepino-integration",
                "nameFA": "وام از طریق سپینو",
                "nameEN": "Via Sepino Digital",
                "category": "digital",
                "categoryFA": "دیجیتال",
                "description": "Access digital loans through Sepino app",
                "descriptionFA": "دسترسی به وام‌های دیجیتال از طریق اپلیکیشن سپینو",
                "guarantor": False,
                "processingTime": "فوری",
                "redirectTo": "sepino"
            },
            {
                "id": "vam-tafahi",
                "nameFA": "وام تفاهی",
                "nameEN": "Agreement Loan",
                "category": "corporate",
                "categoryFA": "شرکتی",
                "minAmount": "100,000,000",
                "maxAmount": "5,000,000,000",
                "minAmountNumeric": 100000000,
                "maxAmountNumeric": 5000000000,
                "interestRate": "18-23%",
                "minTerm": "12 ماه",
                "maxTerm": "60 ماه",
                "guarantor": True,
                "description": "Corporate agreement-based loan",
                "descriptionFA": "وام شرکتی بر اساس تفاهم‌نامه",
                "requirements": ["تفاهم‌نامه با شرکت", "ضمانت شرکتی"],
                "processingTime": "۷-۱۴ روز کاری"
            },
            {
                "id": "vam-kala",
                "nameFA": "وام خرید کالا",
                "nameEN": "Consumer Goods Loan",
                "category": "consumer",
                "categoryFA": "خرید کالا",
                "minAmount": "10,000,000",
                "maxAmount": "200,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 200000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": True,
                "description": "Loan for purchasing consumer goods",
                "descriptionFA": "وام برای خرید کالای مصرفی",
                "requirements": ["فاکتور خرید", "ضامن"],
                "processingTime": "۳-۵ روز کاری"
            },
            {
                "id": "vam-daneshjoyi",
                "nameFA": "وام دانشجویی",
                "nameEN": "Student Loan",
                "category": "student",
                "categoryFA": "دانشجویی",
                "minAmount": "5,000,000",
                "maxAmount": "50,000,000",
                "minAmountNumeric": 5000000,
                "maxAmountNumeric": 50000000,
                "interestRate": "4%",
                "interestRateNumeric": 4,
                "minTerm": "12 ماه",
                "maxTerm": "60 ماه",
                "guarantor": True,
                "description": "Subsidized loan for students",
                "descriptionFA": "وام یارانه‌ای برای دانشجویان",
                "requirements": ["گواهی اشتغال به تحصیل", "ضامن کارمند"],
                "processingTime": "۵-۱۰ روز کاری"
            }
        ],
        "generalRequirements": {
            "creditRating": True,
            "guarantor": True,
            "check": True,
            "minAge": 18,
            "maxAge": 70
        },
        "features": ["شبکه گسترده شعب", "بانکداری دیجیتال سپینو", "خدمات ارزی"],
        "loansCount": 9,
        "lastUpdated": "2026-02-02"
    },
    {
        "id": "bank-parsian",
        "nameFA": "بانک پارسیان",
        "nameEN": "Bank Parsian",
        "category": "traditional-banks",
        "type": "private",
        "website": "https://parsian-bank.ir",
        "description": "Bank Parsian is a leading private bank known for innovative banking solutions",
        "descriptionFA": "بانک پارسیان یکی از بانک‌های خصوصی پیشرو با راهکارهای نوآورانه بانکی است",
        "loanTypes": [
            {
                "id": "pars-vam",
                "nameFA": "پارس وام",
                "nameEN": "Pars Loan",
                "category": "general",
                "categoryFA": "وام عمومی",
                "minAmount": "20,000,000",
                "maxAmount": "500,000,000",
                "minAmountNumeric": 20000000,
                "maxAmountNumeric": 500000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "48 ماه",
                "guarantor": True,
                "description": "General purpose loan",
                "descriptionFA": "وام با هدف عمومی",
                "requirements": ["ضامن معتبر", "میانگین حساب"],
                "processingTime": "۳-۵ روز کاری"
            },
            {
                "id": "pezhvak",
                "nameFA": "طرح پژواک",
                "nameEN": "Pezhvak Plan",
                "category": "deposit-based",
                "categoryFA": "بر اساس سپرده",
                "minAmount": "10,000,000",
                "maxAmount": "300,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 300000000,
                "interestRate": "18-23%",
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": False,
                "description": "Loan based on term deposit",
                "descriptionFA": "وام بر اساس سپرده مدت‌دار",
                "requirements": ["سپرده مدت‌دار در بانک پارسیان"],
                "processingTime": "۲۴ ساعت"
            },
            {
                "id": "navid",
                "nameFA": "طرح نوید",
                "nameEN": "Navid Plan",
                "category": "promise",
                "categoryFA": "طرح نوید",
                "minAmount": "50,000,000",
                "maxAmount": "1,000,000,000",
                "minAmountNumeric": 50000000,
                "maxAmountNumeric": 1000000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "24 ماه",
                "maxTerm": "84 ماه",
                "guarantor": True,
                "description": "Long-term promise-based loan",
                "descriptionFA": "وام بلندمدت بر اساس تعهد",
                "requirements": ["تعهد بازپرداخت", "ضمانت‌نامه"],
                "processingTime": "۵-۷ روز کاری"
            },
            {
                "id": "danesh-bonian",
                "nameFA": "تسهیلات دانش بنیان",
                "nameEN": "Knowledge-Based Loan",
                "category": "innovation",
                "categoryFA": "دانش بنیان",
                "minAmount": "100,000,000",
                "maxAmount": "5,000,000,000",
                "minAmountNumeric": 100000000,
                "maxAmountNumeric": 5000000000,
                "interestRate": "15%",
                "interestRateNumeric": 15,
                "minTerm": "24 ماه",
                "maxTerm": "84 ماه",
                "guarantor": True,
                "description": "Special loan for knowledge-based companies",
                "descriptionFA": "وام ویژه شرکت‌های دانش بنیان",
                "requirements": ["تأییدیه دانش بنیان", "طرح توجیهی"],
                "processingTime": "۱۴-۲۱ روز کاری"
            },
            {
                "id": "kharid-mahal-kar",
                "nameFA": "وام خرید محل کار",
                "nameEN": "Workplace Purchase Loan",
                "category": "business-property",
                "categoryFA": "خرید محل کسب",
                "minAmount": "200,000,000",
                "maxAmount": "5,000,000,000",
                "minAmountNumeric": 200000000,
                "maxAmountNumeric": 5000000000,
                "interestRate": "18%",
                "interestRateNumeric": 18,
                "minTerm": "60 ماه",
                "maxTerm": "180 ماه",
                "guarantor": False,
                "collateral": True,
                "description": "Loan for purchasing business premises",
                "descriptionFA": "وام خرید محل کسب و کار",
                "requirements": ["سند ملک", "ارزیابی", "مجوز کسب"],
                "processingTime": "۱۴-۳۰ روز کاری"
            },
            {
                "id": "kharid-kala",
                "nameFA": "وام خرید کالا",
                "nameEN": "Consumer Loan",
                "category": "consumer",
                "categoryFA": "خرید کالا",
                "minAmount": "10,000,000",
                "maxAmount": "150,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 150000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": True,
                "description": "Consumer goods purchase loan",
                "descriptionFA": "وام خرید کالای مصرفی",
                "requirements": ["فاکتور خرید", "ضامن"],
                "processingTime": "۳-۵ روز کاری"
            }
        ],
        "generalRequirements": {
            "creditRating": True,
            "guarantor": True,
            "minAge": 18,
            "maxAge": 70
        },
        "features": ["بانکداری نوآورانه", "تسهیلات دانش بنیان", "خدمات VIP"],
        "loansCount": 6,
        "lastUpdated": "2026-02-02"
    },
    {
        "id": "bank-pasargad",
        "nameFA": "بانک پاسارگاد",
        "nameEN": "Bank Pasargad",
        "category": "traditional-banks",
        "type": "private",
        "website": "https://bpi.ir",
        "description": "Bank Pasargad is a premium private bank with focus on quality service and digital banking",
        "descriptionFA": "بانک پاسارگاد بانک خصوصی ممتاز با تمرکز بر کیفیت خدمات و بانکداری دیجیتال است",
        "loanTypes": [
            {
                "id": "vam-mehregan",
                "nameFA": "طرح مهرگان",
                "nameEN": "Mehregan Plan",
                "category": "deposit-based",
                "categoryFA": "بر اساس سپرده",
                "minAmount": "10,000,000",
                "maxAmount": "500,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 500000000,
                "interestRate": "18-23%",
                "minTerm": "12 ماه",
                "maxTerm": "60 ماه",
                "guarantor": False,
                "description": "Loan based on deposit average",
                "descriptionFA": "وام بر اساس میانگین سپرده",
                "requirements": ["سپرده در بانک پاسارگاد", "حداقل ۳ ماه میانگین"],
                "processingTime": "۲-۳ روز کاری"
            },
            {
                "id": "weepod-integration",
                "nameFA": "وام از طریق ویپاد",
                "nameEN": "Via Weepod Digital",
                "category": "digital",
                "categoryFA": "دیجیتال",
                "description": "Access digital loans through Weepod app",
                "descriptionFA": "دسترسی به وام‌های دیجیتال از طریق اپلیکیشن ویپاد",
                "guarantor": False,
                "processingTime": "فوری",
                "redirectTo": "weepod"
            },
            {
                "id": "vam-rahni-pasargad",
                "nameFA": "وام رهنی پاسارگاد",
                "nameEN": "Pasargad Mortgage",
                "category": "mortgage",
                "categoryFA": "وام رهنی",
                "minAmount": "500,000,000",
                "maxAmount": "10,000,000,000",
                "minAmountNumeric": 500000000,
                "maxAmountNumeric": 10000000000,
                "interestRate": "18%",
                "interestRateNumeric": 18,
                "minTerm": "60 ماه",
                "maxTerm": "240 ماه",
                "guarantor": False,
                "collateral": True,
                "description": "Large mortgage loan with property collateral",
                "descriptionFA": "وام رهنی بزرگ با وثیقه ملکی",
                "requirements": ["سند ملک", "ارزیابی", "بیمه"],
                "processingTime": "۱۴-۳۰ روز کاری"
            }
        ],
        "generalRequirements": {
            "creditRating": True,
            "minAge": 18,
            "maxAge": 70
        },
        "features": ["بانکداری دیجیتال ویپاد", "خدمات VIP", "شعب مدرن"],
        "loansCount": 3,
        "lastUpdated": "2026-02-02"
    },
    {
        "id": "bank-karafarin",
        "nameFA": "بانک کارآفرین",
        "nameEN": "Bank Karafarin",
        "category": "traditional-banks",
        "type": "private",
        "website": "https://karafarinbank.ir",
        "description": "Bank Karafarin specializes in SME and entrepreneurship financing",
        "descriptionFA": "بانک کارآفرین در تأمین مالی کسب و کارهای کوچک و متوسط و کارآفرینی تخصص دارد",
        "loanTypes": [
            {
                "id": "vam-karafarin",
                "nameFA": "وام کارآفرینی",
                "nameEN": "Entrepreneurship Loan",
                "category": "business",
                "categoryFA": "کارآفرینی",
                "minAmount": "50,000,000",
                "maxAmount": "2,000,000,000",
                "minAmountNumeric": 50000000,
                "maxAmountNumeric": 2000000000,
                "interestRate": "18%",
                "interestRateNumeric": 18,
                "minTerm": "24 ماه",
                "maxTerm": "84 ماه",
                "guarantor": True,
                "description": "Startup and SME financing",
                "descriptionFA": "تأمین مالی استارتاپ‌ها و کسب و کارهای کوچک",
                "requirements": ["طرح توجیهی", "مجوز کسب", "ضمانت"],
                "processingTime": "۷-۱۴ روز کاری"
            },
            {
                "id": "vam-sarmayeh-gardan",
                "nameFA": "وام سرمایه در گردش",
                "nameEN": "Working Capital Loan",
                "category": "working-capital",
                "categoryFA": "سرمایه در گردش",
                "minAmount": "100,000,000",
                "maxAmount": "5,000,000,000",
                "minAmountNumeric": 100000000,
                "maxAmountNumeric": 5000000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": True,
                "description": "Working capital for businesses",
                "descriptionFA": "سرمایه در گردش برای کسب و کارها",
                "requirements": ["صورت‌های مالی", "ضمانت‌نامه بانکی"],
                "processingTime": "۵-۱۰ روز کاری"
            },
            {
                "id": "vam-tajhizat",
                "nameFA": "وام خرید تجهیزات",
                "nameEN": "Equipment Financing",
                "category": "equipment",
                "categoryFA": "خرید تجهیزات",
                "minAmount": "100,000,000",
                "maxAmount": "3,000,000,000",
                "minAmountNumeric": 100000000,
                "maxAmountNumeric": 3000000000,
                "interestRate": "18%",
                "interestRateNumeric": 18,
                "minTerm": "24 ماه",
                "maxTerm": "72 ماه",
                "guarantor": True,
                "description": "Loan for purchasing business equipment",
                "descriptionFA": "وام خرید تجهیزات کسب و کار",
                "requirements": ["پیش‌فاکتور تجهیزات", "ضمانت"],
                "processingTime": "۷-۱۴ روز کاری"
            },
            {
                "id": "vam-personal",
                "nameFA": "وام شخصی",
                "nameEN": "Personal Loan",
                "category": "personal",
                "categoryFA": "شخصی",
                "minAmount": "20,000,000",
                "maxAmount": "300,000,000",
                "minAmountNumeric": 20000000,
                "maxAmountNumeric": 300000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "48 ماه",
                "guarantor": True,
                "description": "Personal loan for individual needs",
                "descriptionFA": "وام شخصی برای نیازهای فردی",
                "requirements": ["ضامن معتبر", "فیش حقوقی"],
                "processingTime": "۳-۵ روز کاری"
            },
            {
                "id": "vam-mehr-karafarin",
                "nameFA": "قرض‌الحسنه کارآفرین",
                "nameEN": "Karafarin Qarz",
                "category": "zero-interest",
                "categoryFA": "قرض‌الحسنه",
                "minAmount": "10,000,000",
                "maxAmount": "100,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 100000000,
                "interestRate": "0%",
                "interestRateNumeric": 0,
                "fee": "4%",
                "minTerm": "12 ماه",
                "maxTerm": "48 ماه",
                "guarantor": True,
                "description": "Zero interest welfare loan",
                "descriptionFA": "قرض‌الحسنه رفاهی",
                "requirements": ["ضامن", "سفته"],
                "processingTime": "۳-۵ روز کاری"
            }
        ],
        "generalRequirements": {
            "creditRating": True,
            "guarantor": True,
            "minAge": 18,
            "maxAge": 70
        },
        "features": ["تخصص در SME", "تسهیلات کارآفرینی", "مشاوره کسب و کار"],
        "loansCount": 5,
        "lastUpdated": "2026-02-02"
    },
    {
        "id": "bank-iran-zamin",
        "nameFA": "بانک ایران زمین",
        "nameEN": "Bank Iran Zamin",
        "category": "traditional-banks",
        "type": "private",
        "website": "https://izbank.ir",
        "description": "Bank Iran Zamin offers diverse loan products with competitive rates",
        "descriptionFA": "بانک ایران زمین محصولات تسهیلاتی متنوع با نرخ‌های رقابتی ارائه می‌دهد",
        "loanTypes": [
            {
                "id": "vam-foori-iz",
                "nameFA": "وام فوری ایران زمین",
                "nameEN": "Iran Zamin Quick Loan",
                "category": "quick",
                "categoryFA": "وام سریع",
                "minAmount": "10,000,000",
                "maxAmount": "100,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 100000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": True,
                "description": "Quick processing retail loan",
                "descriptionFA": "وام خرد با پردازش سریع",
                "requirements": ["ضامن", "چک"],
                "processingTime": "۲-۳ روز کاری"
            },
            {
                "id": "vam-maskan-iz",
                "nameFA": "وام مسکن ایران زمین",
                "nameEN": "Iran Zamin Housing Loan",
                "category": "housing",
                "categoryFA": "وام مسکن",
                "minAmount": "500,000,000",
                "maxAmount": "3,000,000,000",
                "minAmountNumeric": 500000000,
                "maxAmountNumeric": 3000000000,
                "interestRate": "18%",
                "interestRateNumeric": 18,
                "minTerm": "60 ماه",
                "maxTerm": "180 ماه",
                "guarantor": False,
                "collateral": True,
                "description": "Housing loan with property collateral",
                "descriptionFA": "وام مسکن با رهن ملک",
                "requirements": ["سند ملک", "ارزیابی"],
                "processingTime": "۱۴-۲۱ روز کاری"
            },
            {
                "id": "vam-khodro-iz",
                "nameFA": "وام خودرو ایران زمین",
                "nameEN": "Iran Zamin Auto Loan",
                "category": "auto",
                "categoryFA": "وام خودرو",
                "minAmount": "100,000,000",
                "maxAmount": "500,000,000",
                "minAmountNumeric": 100000000,
                "maxAmountNumeric": 500000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "60 ماه",
                "guarantor": False,
                "collateral": True,
                "description": "Auto loan with vehicle collateral",
                "descriptionFA": "وام خودرو با وثیقه خودرو",
                "requirements": ["پیش‌پرداخت", "بیمه بدنه"],
                "processingTime": "۵-۷ روز کاری"
            },
            {
                "id": "vam-tafahi-iz",
                "nameFA": "وام تفاهی",
                "nameEN": "Corporate Agreement Loan",
                "category": "corporate",
                "categoryFA": "شرکتی",
                "minAmount": "100,000,000",
                "maxAmount": "2,000,000,000",
                "minAmountNumeric": 100000000,
                "maxAmountNumeric": 2000000000,
                "interestRate": "18-23%",
                "minTerm": "12 ماه",
                "maxTerm": "60 ماه",
                "guarantor": True,
                "description": "Corporate loan based on agreement",
                "descriptionFA": "وام شرکتی بر اساس تفاهم‌نامه",
                "requirements": ["تفاهم‌نامه", "ضمانت شرکتی"],
                "processingTime": "۷-۱۴ روز کاری"
            },
            {
                "id": "vam-mehr-iz",
                "nameFA": "قرض‌الحسنه ایران زمین",
                "nameEN": "Iran Zamin Qarz",
                "category": "zero-interest",
                "categoryFA": "قرض‌الحسنه",
                "minAmount": "10,000,000",
                "maxAmount": "100,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 100000000,
                "interestRate": "0%",
                "interestRateNumeric": 0,
                "fee": "4%",
                "minTerm": "12 ماه",
                "maxTerm": "48 ماه",
                "guarantor": True,
                "description": "Zero interest welfare loan",
                "descriptionFA": "قرض‌الحسنه رفاهی",
                "requirements": ["ضامن", "سفته"],
                "processingTime": "۳-۵ روز کاری"
            },
            {
                "id": "cart-etebari-iz",
                "nameFA": "کارت اعتباری ایران زمین",
                "nameEN": "Iran Zamin Credit Card",
                "category": "credit-card",
                "categoryFA": "کارت اعتباری",
                "minAmount": "10,000,000",
                "maxAmount": "200,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 200000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": True,
                "description": "Revolving credit card",
                "descriptionFA": "کارت اعتباری گردشی",
                "requirements": ["ضامن", "میانگین حساب"],
                "processingTime": "۵-۷ روز کاری"
            },
            {
                "id": "vam-kala-iz",
                "nameFA": "وام خرید کالا",
                "nameEN": "Consumer Goods Loan",
                "category": "consumer",
                "categoryFA": "خرید کالا",
                "minAmount": "10,000,000",
                "maxAmount": "150,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 150000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": True,
                "description": "Consumer goods loan",
                "descriptionFA": "وام خرید کالای مصرفی",
                "requirements": ["فاکتور خرید", "ضامن"],
                "processingTime": "۳-۵ روز کاری"
            },
            {
                "id": "vam-ezdevaj-iz",
                "nameFA": "وام ازدواج",
                "nameEN": "Marriage Loan",
                "category": "marriage",
                "categoryFA": "وام ازدواج",
                "minAmount": "150,000,000",
                "maxAmount": "500,000,000",
                "minAmountNumeric": 150000000,
                "maxAmountNumeric": 500000000,
                "interestRate": "4%",
                "interestRateNumeric": 4,
                "minTerm": "60 ماه",
                "maxTerm": "120 ماه",
                "guarantor": True,
                "description": "Government-backed marriage loan",
                "descriptionFA": "وام ازدواج با حمایت دولت",
                "requirements": ["عقدنامه", "ضامن کارمند"],
                "processingTime": "۷-۱۴ روز کاری"
            },
            {
                "id": "vam-daneshjoyi-iz",
                "nameFA": "وام دانشجویی",
                "nameEN": "Student Loan",
                "category": "student",
                "categoryFA": "دانشجویی",
                "minAmount": "5,000,000",
                "maxAmount": "50,000,000",
                "minAmountNumeric": 5000000,
                "maxAmountNumeric": 50000000,
                "interestRate": "4%",
                "interestRateNumeric": 4,
                "minTerm": "12 ماه",
                "maxTerm": "60 ماه",
                "guarantor": True,
                "description": "Subsidized student loan",
                "descriptionFA": "وام یارانه‌ای دانشجویان",
                "requirements": ["گواهی تحصیل", "ضامن"],
                "processingTime": "۵-۱۰ روز کاری"
            }
        ],
        "generalRequirements": {
            "creditRating": True,
            "guarantor": True,
            "minAge": 18,
            "maxAge": 70
        },
        "features": ["تنوع محصولات", "نرخ رقابتی", "شعب گسترده"],
        "loansCount": 9,
        "lastUpdated": "2026-02-02"
    },
    {
        "id": "bank-day",
        "nameFA": "بانک دی",
        "nameEN": "Bank Day",
        "category": "traditional-banks",
        "type": "private",
        "website": "https://bank-day.ir",
        "description": "Bank Day is a private bank focused on corporate and retail banking services",
        "descriptionFA": "بانک دی یک بانک خصوصی با تمرکز بر خدمات بانکی شرکتی و خرد است",
        "loanTypes": [
            {
                "id": "vam-foori-day",
                "nameFA": "وام فوری دی",
                "nameEN": "Day Quick Loan",
                "category": "quick",
                "categoryFA": "وام سریع",
                "minAmount": "10,000,000",
                "maxAmount": "100,000,000",
                "minAmountNumeric": 10000000,
                "maxAmountNumeric": 100000000,
                "interestRate": "23%",
                "interestRateNumeric": 23,
                "minTerm": "12 ماه",
                "maxTerm": "36 ماه",
                "guarantor": True,
                "description": "Quick retail loan",
                "descriptionFA": "وام خرد با پردازش سریع",
                "requirements": ["ضامن", "میانگین حساب"],
                "processingTime": "۲-۴ روز کاری"
            },
            {
                "id": "vam-sherkati-day",
                "nameFA": "وام شرکتی دی",
                "nameEN": "Day Corporate Loan",
                "category": "corporate",
                "categoryFA": "شرکتی",
                "minAmount": "100,000,000",
                "maxAmount": "5,000,000,000",
                "minAmountNumeric": 100000000,
                "maxAmountNumeric": 5000000000,
                "interestRate": "18-23%",
                "minTerm": "12 ماه",
                "maxTerm": "60 ماه",
                "guarantor": True,
                "description": "Corporate financing",
                "descriptionFA": "تأمین مالی شرکت‌ها",
                "requirements": ["صورت‌های مالی", "ضمانت‌نامه"],
                "processingTime": "۷-۱۴ روز کاری"
            }
        ],
        "generalRequirements": {
            "creditRating": True,
            "guarantor": True,
            "minAge": 18,
            "maxAge": 70
        },
        "features": ["تسهیلات شرکتی", "خدمات خرد"],
        "loansCount": 2,
        "lastUpdated": "2026-02-02"
    },
    {
        "id": "bank-tosee-saderat",
        "nameFA": "بانک توسعه صادرات",
        "nameEN": "Export Development Bank of Iran",
        "category": "traditional-banks",
        "type": "state-owned",
        "website": "https://edbi.ir",
        "description": "Export Development Bank specializes in financing export and international trade",
        "descriptionFA": "بانک توسعه صادرات در تأمین مالی صادرات و تجارت بین‌المللی تخصص دارد",
        "loanTypes": [
            {
                "id": "vam-saderat",
                "nameFA": "تسهیلات صادراتی",
                "nameEN": "Export Financing",
                "category": "export",
                "categoryFA": "تسهیلات صادراتی",
                "minAmount": "500,000,000",
                "maxAmount": "50,000,000,000",
                "minAmountNumeric": 500000000,
                "maxAmountNumeric": 50000000000,
                "interestRate": "15-18%",
                "minTerm": "12 ماه",
                "maxTerm": "60 ماه",
                "guarantor": True,
                "description": "Financing for exporters",
                "descriptionFA": "تأمین مالی صادرکنندگان",
                "requirements": ["کارت بازرگانی", "قرارداد صادراتی", "ضمانت‌نامه"],
                "processingTime": "۱۴-۳۰ روز کاری"
            }
        ],
        "generalRequirements": {
            "exportLicense": True,
            "guarantor": True
        },
        "features": ["تخصص در صادرات", "تسهیلات ارزی", "ضمانت‌نامه صادراتی"],
        "loansCount": 1,
        "lastUpdated": "2026-02-02"
    }
]


async def update_banks():
    """Update all banks in MongoDB with comprehensive data."""
    client = AsyncIOMotorClient(MONGODB_URL)
    db = client[DATABASE_NAME]
    banks_collection = db["banks"]

    print(f"Connecting to MongoDB: {DATABASE_NAME}")

    # Clear existing data
    await banks_collection.delete_many({})
    print("Cleared existing bank data")

    # Insert new data
    for bank in BANKS_DATA:
        # Update loansCount based on actual loanTypes
        bank["loansCount"] = len(bank.get("loanTypes", []))
        await banks_collection.insert_one(bank)
        print(f"Inserted: {bank['nameFA']} ({bank['id']}) - {bank['loansCount']} loans")

    print(f"\nTotal banks inserted: {len(BANKS_DATA)}")

    # Count total loans
    total_loans = sum(len(bank.get("loanTypes", [])) for bank in BANKS_DATA)
    print(f"Total loan products: {total_loans}")

    client.close()


if __name__ == "__main__":
    asyncio.run(update_banks())
